# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: New Features 🎉
      labels:
        - "*"
    - title: Bug Fixes 🛠
      labels:
        - bug
        - crash
