//
// PlaylistsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class PlaylistsAPI {
    /**
     Adds items to a playlist.

     - parameter playlistId: (path) The playlist id. 
     - parameter ids: (query) Item id, comma delimited. (optional)
     - parameter userId: (query) The userId. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func addToPlaylist(playlistId: UUID, ids: [UUID]? = nil, userId: UUID? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        addToPlaylistWithRequestBuilder(playlistId: playlistId, ids: ids, userId: userId).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Adds items to a playlist.
     - POST /Playlists/{playlistId}/Items
     - 

     - API Key:
       - type: apiKey X-Emby-Authorization 
       - name: CustomAuthentication
     - parameter playlistId: (path) The playlist id. 
     - parameter ids: (query) Item id, comma delimited. (optional)
     - parameter userId: (query) The userId. (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func addToPlaylistWithRequestBuilder(playlistId: UUID, ids: [UUID]? = nil, userId: UUID? = nil) -> RequestBuilder<Void> {
        var path = "/Playlists/{playlistId}/Items"
        let playlistIdPreEscape = "\(playlistId)"
        let playlistIdPostEscape = playlistIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{playlistId}", with: playlistIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "ids": ids, 
                        "userId": userId
        ])


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     Creates a new playlist.

     - parameter body: (body) The create playlist payload. (optional)
     - parameter name: (query) The playlist name. (optional)
     - parameter ids: (query) The item ids. (optional)
     - parameter userId: (query) The user id. (optional)
     - parameter mediaType: (query) The media type. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createPlaylist(body: PlaylistsBody? = nil, name: String? = nil, ids: [UUID]? = nil, userId: UUID? = nil, mediaType: String? = nil, completion: @escaping ((_ data: PlaylistCreationResult?,_ error: Error?) -> Void)) {
        createPlaylistWithRequestBuilder(body: body, name: name, ids: ids, userId: userId, mediaType: mediaType).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Creates a new playlist.
     - POST /Playlists

     - API Key:
       - type: apiKey X-Emby-Authorization 
       - name: CustomAuthentication
     - examples: [{contentType=application/json, example={
  "Id" : "Id"
}}]
     - parameter body: (body) The create playlist payload. (optional)
     - parameter name: (query) The playlist name. (optional)
     - parameter ids: (query) The item ids. (optional)
     - parameter userId: (query) The user id. (optional)
     - parameter mediaType: (query) The media type. (optional)

     - returns: RequestBuilder<PlaylistCreationResult> 
     */
    open class func createPlaylistWithRequestBuilder(body: PlaylistsBody? = nil, name: String? = nil, ids: [UUID]? = nil, userId: UUID? = nil, mediaType: String? = nil) -> RequestBuilder<PlaylistCreationResult> {
        let path = "/Playlists"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "name": name, 
                        "ids": ids, 
                        "userId": userId, 
                        "mediaType": mediaType
        ])


        let requestBuilder: RequestBuilder<PlaylistCreationResult>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**
     Gets the original items of a playlist.

     - parameter playlistId: (path) The playlist id. 
     - parameter userId: (query) User id. 
     - parameter startIndex: (query) Optional. The record index to start at. All items with a lower index will be dropped from the results. (optional)
     - parameter limit: (query) Optional. The maximum number of records to return. (optional)
     - parameter fields: (query) Optional. Specify additional fields of information to return in the output. (optional)
     - parameter enableImages: (query) Optional. Include image information in output. (optional)
     - parameter enableUserData: (query) Optional. Include user data. (optional)
     - parameter imageTypeLimit: (query) Optional. The max number of images to return, per image type. (optional)
     - parameter enableImageTypes: (query) Optional. The image types to include in the output. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getPlaylistItems(playlistId: UUID, userId: UUID, startIndex: Int? = nil, limit: Int? = nil, fields: [ItemFields]? = nil, enableImages: Bool? = nil, enableUserData: Bool? = nil, imageTypeLimit: Int? = nil, enableImageTypes: [ImageType]? = nil, completion: @escaping ((_ data: BaseItemDtoQueryResult?,_ error: Error?) -> Void)) {
        getPlaylistItemsWithRequestBuilder(playlistId: playlistId, userId: userId, startIndex: startIndex, limit: limit, fields: fields, enableImages: enableImages, enableUserData: enableUserData, imageTypeLimit: imageTypeLimit, enableImageTypes: enableImageTypes).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Gets the original items of a playlist.
     - GET /Playlists/{playlistId}/Items
     - 

     - API Key:
       - type: apiKey X-Emby-Authorization 
       - name: CustomAuthentication
     - examples: [{contentType=application/json, example={
  "TotalRecordCount" : 7,
  "StartIndex" : 5,
  "Items" : [ {
    "SeasonName" : "SeasonName",
    "PremiereDate" : "2000-01-23T04:56:07.000+00:00",
    "CriticRating" : 9.018348,
    "AirTime" : "AirTime",
    "Studios" : [ {
      "Id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
      "Name" : "Name"
    }, {
      "Id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
      "Name" : "Name"
    } ],
    "CameraMake" : "CameraMake",
    "Aperture" : 1.041444916118296,
    "ChannelPrimaryImageTag" : "ChannelPrimaryImageTag",
    "ExtraType" : "ExtraType",
    "ParentBackdropItemId" : "ParentBackdropItemId",
    "Etag" : "Etag",
    "ParentLogoImageTag" : "ParentLogoImageTag",
    "ExposureTime" : 6.628464275087742,
    "IsoType" : "",
    "MediaType" : "MediaType",
    "Tags" : [ "Tags", "Tags" ],
    "ImageBlurHashes" : {
      "Art" : {
        "key" : "Art"
      },
      "Banner" : {
        "key" : "Banner"
      },
      "Thumb" : {
        "key" : "Thumb"
      },
      "Chapter" : {
        "key" : "Chapter"
      },
      "BoxRear" : {
        "key" : "BoxRear"
      },
      "Box" : {
        "key" : "Box"
      },
      "Profile" : {
        "key" : "Profile"
      },
      "Logo" : {
        "key" : "Logo"
      },
      "Disc" : {
        "key" : "Disc"
      },
      "Primary" : {
        "key" : "Primary"
      },
      "Screenshot" : {
        "key" : "Screenshot"
      },
      "Backdrop" : {
        "key" : "Backdrop"
      },
      "Menu" : {
        "key" : "Menu"
      }
    },
    "Status" : "Status",
    "IndexNumberEnd" : 6,
    "ArtistItems" : [ null, null ],
    "MediaSources" : [ {
      "EncoderPath" : "EncoderPath",
      "RequiredHttpHeaders" : {
        "key" : "RequiredHttpHeaders"
      },
      "RunTimeTicks" : 5,
      "MediaStreams" : [ {
        "VideoRange" : "VideoRange",
        "CodecTimeBase" : "CodecTimeBase",
        "ColorSpace" : "ColorSpace",
        "Index" : 7,
        "ColorRange" : "ColorRange",
        "localizedForced" : "localizedForced",
        "BitDepth" : 9,
        "Channels" : 4,
        "Profile" : "Profile",
        "SupportsExternalStream" : true,
        "localizedDefault" : "localizedDefault",
        "DeliveryUrl" : "DeliveryUrl",
        "Codec" : "Codec",
        "ColorPrimaries" : "ColorPrimaries",
        "SampleRate" : 7,
        "Language" : "Language",
        "IsTextSubtitleStream" : true,
        "IsAnamorphic" : true,
        "NalLengthSize" : "NalLengthSize",
        "Height" : 1,
        "PixelFormat" : "PixelFormat",
        "RefFrames" : 3,
        "IsAVC" : true,
        "Width" : 1,
        "TimeBase" : "TimeBase",
        "ColorTransfer" : "ColorTransfer",
        "CodecTag" : "CodecTag",
        "IsDefault" : true,
        "Path" : "Path",
        "Comment" : "Comment",
        "DeliveryMethod" : "",
        "IsExternalUrl" : true,
        "DisplayTitle" : "DisplayTitle",
        "IsForced" : true,
        "ChannelLayout" : "ChannelLayout",
        "localizedUndefined" : "localizedUndefined",
        "PacketLength" : 2,
        "Title" : "Title",
        "RealFrameRate" : 6.846853,
        "AspectRatio" : "AspectRatio",
        "AverageFrameRate" : 1.4894159,
        "Type" : "",
        "Score" : 1,
        "IsExternal" : true,
        "IsInterlaced" : true,
        "Level" : 4.965218492984954,
        "BitRate" : 7
      }, {
        "VideoRange" : "VideoRange",
        "CodecTimeBase" : "CodecTimeBase",
        "ColorSpace" : "ColorSpace",
        "Index" : 7,
        "ColorRange" : "ColorRange",
        "localizedForced" : "localizedForced",
        "BitDepth" : 9,
        "Channels" : 4,
        "Profile" : "Profile",
        "SupportsExternalStream" : true,
        "localizedDefault" : "localizedDefault",
        "DeliveryUrl" : "DeliveryUrl",
        "Codec" : "Codec",
        "ColorPrimaries" : "ColorPrimaries",
        "SampleRate" : 7,
        "Language" : "Language",
        "IsTextSubtitleStream" : true,
        "IsAnamorphic" : true,
        "NalLengthSize" : "NalLengthSize",
        "Height" : 1,
        "PixelFormat" : "PixelFormat",
        "RefFrames" : 3,
        "IsAVC" : true,
        "Width" : 1,
        "TimeBase" : "TimeBase",
        "ColorTransfer" : "ColorTransfer",
        "CodecTag" : "CodecTag",
        "IsDefault" : true,
        "Path" : "Path",
        "Comment" : "Comment",
        "DeliveryMethod" : "",
        "IsExternalUrl" : true,
        "DisplayTitle" : "DisplayTitle",
        "IsForced" : true,
        "ChannelLayout" : "ChannelLayout",
        "localizedUndefined" : "localizedUndefined",
        "PacketLength" : 2,
        "Title" : "Title",
        "RealFrameRate" : 6.846853,
        "AspectRatio" : "AspectRatio",
        "AverageFrameRate" : 1.4894159,
        "Type" : "",
        "Score" : 1,
        "IsExternal" : true,
        "IsInterlaced" : true,
        "Level" : 4.965218492984954,
        "BitRate" : 7
      } ],
      "Size" : 5,
      "Video3DFormat" : "",
      "BufferMs" : 2,
      "Timestamp" : "",
      "Name" : "Name",
      "RequiresOpening" : true,
      "SupportsDirectStream" : true,
      "VideoType" : "",
      "RequiresClosing" : true,
      "Container" : "Container",
      "IsoType" : "",
      "LiveStreamId" : "LiveStreamId",
      "RequiresLooping" : true,
      "Protocol" : "",
      "DefaultSubtitleStreamIndex" : 8,
      "GenPtsInput" : true,
      "IsInfiniteStream" : true,
      "Path" : "Path",
      "IsRemote" : true,
      "EncoderProtocol" : "",
      "IgnoreIndex" : true,
      "SupportsDirectPlay" : true,
      "TranscodingSubProtocol" : "TranscodingSubProtocol",
      "Formats" : [ "Formats", "Formats" ],
      "AnalyzeDurationMs" : 9,
      "Bitrate" : 9,
      "OpenToken" : "OpenToken",
      "SupportsProbing" : true,
      "Type" : "",
      "MediaAttachments" : [ {
        "CodecTag" : "CodecTag",
        "Comment" : "Comment",
        "DeliveryUrl" : "DeliveryUrl",
        "Codec" : "Codec",
        "FileName" : "FileName",
        "Index" : 5,
        "MimeType" : "MimeType"
      }, {
        "CodecTag" : "CodecTag",
        "Comment" : "Comment",
        "DeliveryUrl" : "DeliveryUrl",
        "Codec" : "Codec",
        "FileName" : "FileName",
        "Index" : 5,
        "MimeType" : "MimeType"
      } ],
      "ReadAtNativeFramerate" : true,
      "ETag" : "ETag",
      "TranscodingContainer" : "TranscodingContainer",
      "IgnoreDts" : true,
      "TranscodingUrl" : "TranscodingUrl",
      "Id" : "Id",
      "SupportsTranscoding" : true,
      "DefaultAudioStreamIndex" : 6
    }, {
      "EncoderPath" : "EncoderPath",
      "RequiredHttpHeaders" : {
        "key" : "RequiredHttpHeaders"
      },
      "RunTimeTicks" : 5,
      "MediaStreams" : [ {
        "VideoRange" : "VideoRange",
        "CodecTimeBase" : "CodecTimeBase",
        "ColorSpace" : "ColorSpace",
        "Index" : 7,
        "ColorRange" : "ColorRange",
        "localizedForced" : "localizedForced",
        "BitDepth" : 9,
        "Channels" : 4,
        "Profile" : "Profile",
        "SupportsExternalStream" : true,
        "localizedDefault" : "localizedDefault",
        "DeliveryUrl" : "DeliveryUrl",
        "Codec" : "Codec",
        "ColorPrimaries" : "ColorPrimaries",
        "SampleRate" : 7,
        "Language" : "Language",
        "IsTextSubtitleStream" : true,
        "IsAnamorphic" : true,
        "NalLengthSize" : "NalLengthSize",
        "Height" : 1,
        "PixelFormat" : "PixelFormat",
        "RefFrames" : 3,
        "IsAVC" : true,
        "Width" : 1,
        "TimeBase" : "TimeBase",
        "ColorTransfer" : "ColorTransfer",
        "CodecTag" : "CodecTag",
        "IsDefault" : true,
        "Path" : "Path",
        "Comment" : "Comment",
        "DeliveryMethod" : "",
        "IsExternalUrl" : true,
        "DisplayTitle" : "DisplayTitle",
        "IsForced" : true,
        "ChannelLayout" : "ChannelLayout",
        "localizedUndefined" : "localizedUndefined",
        "PacketLength" : 2,
        "Title" : "Title",
        "RealFrameRate" : 6.846853,
        "AspectRatio" : "AspectRatio",
        "AverageFrameRate" : 1.4894159,
        "Type" : "",
        "Score" : 1,
        "IsExternal" : true,
        "IsInterlaced" : true,
        "Level" : 4.965218492984954,
        "BitRate" : 7
      }, {
        "VideoRange" : "VideoRange",
        "CodecTimeBase" : "CodecTimeBase",
        "ColorSpace" : "ColorSpace",
        "Index" : 7,
        "ColorRange" : "ColorRange",
        "localizedForced" : "localizedForced",
        "BitDepth" : 9,
        "Channels" : 4,
        "Profile" : "Profile",
        "SupportsExternalStream" : true,
        "localizedDefault" : "localizedDefault",
        "DeliveryUrl" : "DeliveryUrl",
        "Codec" : "Codec",
        "ColorPrimaries" : "ColorPrimaries",
        "SampleRate" : 7,
        "Language" : "Language",
        "IsTextSubtitleStream" : true,
        "IsAnamorphic" : true,
        "NalLengthSize" : "NalLengthSize",
        "Height" : 1,
        "PixelFormat" : "PixelFormat",
        "RefFrames" : 3,
        "IsAVC" : true,
        "Width" : 1,
        "TimeBase" : "TimeBase",
        "ColorTransfer" : "ColorTransfer",
        "CodecTag" : "CodecTag",
        "IsDefault" : true,
        "Path" : "Path",
        "Comment" : "Comment",
        "DeliveryMethod" : "",
        "IsExternalUrl" : true,
        "DisplayTitle" : "DisplayTitle",
        "IsForced" : true,
        "ChannelLayout" : "ChannelLayout",
        "localizedUndefined" : "localizedUndefined",
        "PacketLength" : 2,
        "Title" : "Title",
        "RealFrameRate" : 6.846853,
        "AspectRatio" : "AspectRatio",
        "AverageFrameRate" : 1.4894159,
        "Type" : "",
        "Score" : 1,
        "IsExternal" : true,
        "IsInterlaced" : true,
        "Level" : 4.965218492984954,
        "BitRate" : 7
      } ],
      "Size" : 5,
      "Video3DFormat" : "",
      "BufferMs" : 2,
      "Timestamp" : "",
      "Name" : "Name",
      "RequiresOpening" : true,
      "SupportsDirectStream" : true,
      "VideoType" : "",
      "RequiresClosing" : true,
      "Container" : "Container",
      "IsoType" : "",
      "LiveStreamId" : "LiveStreamId",
      "RequiresLooping" : true,
      "Protocol" : "",
      "DefaultSubtitleStreamIndex" : 8,
      "GenPtsInput" : true,
      "IsInfiniteStream" : true,
      "Path" : "Path",
      "IsRemote" : true,
      "EncoderProtocol" : "",
      "IgnoreIndex" : true,
      "SupportsDirectPlay" : true,
      "TranscodingSubProtocol" : "TranscodingSubProtocol",
      "Formats" : [ "Formats", "Formats" ],
      "AnalyzeDurationMs" : 9,
      "Bitrate" : 9,
      "OpenToken" : "OpenToken",
      "SupportsProbing" : true,
      "Type" : "",
      "MediaAttachments" : [ {
        "CodecTag" : "CodecTag",
        "Comment" : "Comment",
        "DeliveryUrl" : "DeliveryUrl",
        "Codec" : "Codec",
        "FileName" : "FileName",
        "Index" : 5,
        "MimeType" : "MimeType"
      }, {
        "CodecTag" : "CodecTag",
        "Comment" : "Comment",
        "DeliveryUrl" : "DeliveryUrl",
        "Codec" : "Codec",
        "FileName" : "FileName",
        "Index" : 5,
        "MimeType" : "MimeType"
      } ],
      "ReadAtNativeFramerate" : true,
      "ETag" : "ETag",
      "TranscodingContainer" : "TranscodingContainer",
      "IgnoreDts" : true,
      "TranscodingUrl" : "TranscodingUrl",
      "Id" : "Id",
      "SupportsTranscoding" : true,
      "DefaultAudioStreamIndex" : 6
    } ],
    "GenreItems" : [ null, null ],
    "OfficialRating" : "OfficialRating",
    "ProgramCount" : 7,
    "ProgramId" : "ProgramId",
    "Longitude" : 9.132027271330688,
    "LockData" : true,
    "FocalLength" : 4.258773108174356,
    "IsNews" : true,
    "ShutterSpeed" : 4.678947989005849,
    "Id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "IsFolder" : true,
    "SeriesTimerId" : "SeriesTimerId",
    "SeriesId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "MediaStreams" : [ null, null ],
    "IsPlaceHolder" : true,
    "CanDownload" : true,
    "SeriesCount" : 8,
    "IsMovie" : true,
    "DateLastMediaAdded" : "2000-01-23T04:56:07.000+00:00",
    "ParentArtImageTag" : "ParentArtImageTag",
    "PlayAccess" : "",
    "SeriesStudio" : "SeriesStudio",
    "IsLive" : true,
    "Width" : 4,
    "ExternalUrls" : [ {
      "Url" : "Url",
      "Name" : "Name"
    }, {
      "Url" : "Url",
      "Name" : "Name"
    } ],
    "RecursiveItemCount" : 6,
    "Path" : "Path",
    "ParentId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "MusicVideoCount" : 3,
    "ScreenshotImageTags" : [ "ScreenshotImageTags", "ScreenshotImageTags" ],
    "EpisodeCount" : 3,
    "IsSeries" : true,
    "ProductionLocations" : [ "ProductionLocations", "ProductionLocations" ],
    "ParentPrimaryImageItemId" : "ParentPrimaryImageItemId",
    "EndDate" : "2000-01-23T04:56:07.000+00:00",
    "SeriesPrimaryImageTag" : "SeriesPrimaryImageTag",
    "ParentThumbItemId" : "ParentThumbItemId",
    "PreferredMetadataLanguage" : "PreferredMetadataLanguage",
    "Type" : "Type",
    "BackdropImageTags" : [ "BackdropImageTags", "BackdropImageTags" ],
    "ParentBackdropImageTags" : [ "ParentBackdropImageTags", "ParentBackdropImageTags" ],
    "AirsBeforeEpisodeNumber" : 1,
    "ChildCount" : 3,
    "Audio" : "",
    "Artists" : [ "Artists", "Artists" ],
    "ChannelType" : "",
    "RunTimeTicks" : 6,
    "AlbumPrimaryImageTag" : "AlbumPrimaryImageTag",
    "Video3DFormat" : "",
    "CumulativeRunTimeTicks" : 3,
    "SourceType" : "SourceType",
    "CanDelete" : true,
    "PlaylistItemId" : "PlaylistItemId",
    "DisplayPreferencesId" : "DisplayPreferencesId",
    "Album" : "Album",
    "Latitude" : 7.260521264802104,
    "SortName" : "SortName",
    "ArtistCount" : 5,
    "Name" : "Name",
    "StartDate" : "2000-01-23T04:56:07.000+00:00",
    "Container" : "Container",
    "ProductionYear" : 1,
    "SeriesName" : "SeriesName",
    "ParentArtItemId" : "ParentArtItemId",
    "AlbumId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "SupportsSync" : true,
    "LocalTrailerCount" : 5,
    "IndexNumber" : 2,
    "CompletionPercentage" : 0.5199002018724985,
    "Genres" : [ "Genres", "Genres" ],
    "SeasonId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "LockedFields" : [ "Cast", "Cast" ],
    "ParentPrimaryImageTag" : "ParentPrimaryImageTag",
    "ProviderIds" : {
      "key" : "ProviderIds"
    },
    "RemoteTrailers" : [ {
      "Url" : "Url",
      "Name" : "Name"
    }, {
      "Url" : "Url",
      "Name" : "Name"
    } ],
    "MediaSourceCount" : 7,
    "CustomRating" : "CustomRating",
    "AirsAfterSeasonNumber" : 6,
    "AirDays" : [ "Sunday", "Sunday" ],
    "ParentLogoItemId" : "ParentLogoItemId",
    "PartCount" : 0,
    "ChannelName" : "ChannelName",
    "EpisodeTitle" : "EpisodeTitle",
    "IsoSpeedRating" : 9,
    "CommunityRating" : 6.4384236,
    "Software" : "Software",
    "Chapters" : [ {
      "StartPositionTicks" : 6,
      "ImageTag" : "ImageTag",
      "ImageDateModified" : "2000-01-23T04:56:07.000+00:00",
      "ImagePath" : "ImagePath",
      "Name" : "Name"
    }, {
      "StartPositionTicks" : 6,
      "ImageTag" : "ImageTag",
      "ImageDateModified" : "2000-01-23T04:56:07.000+00:00",
      "ImagePath" : "ImagePath",
      "Name" : "Name"
    } ],
    "SongCount" : 3,
    "Taglines" : [ "Taglines", "Taglines" ],
    "AirsBeforeSeasonNumber" : 0,
    "PreferredMetadataCountryCode" : "PreferredMetadataCountryCode",
    "CameraModel" : "CameraModel",
    "ChannelNumber" : "ChannelNumber",
    "UserData" : "",
    "TimerId" : "TimerId",
    "DateCreated" : "2000-01-23T04:56:07.000+00:00",
    "HasSubtitles" : true,
    "ParentThumbImageTag" : "ParentThumbImageTag",
    "IsSports" : true,
    "ChannelId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "ParentIndexNumber" : 6,
    "VideoType" : "",
    "AlbumArtists" : [ null, null ],
    "ServerId" : "ServerId",
    "Number" : "Number",
    "AlbumCount" : 7,
    "IsRepeat" : true,
    "CollectionType" : "CollectionType",
    "PrimaryImageAspectRatio" : 7.143538047012306,
    "Height" : 0,
    "IsKids" : true,
    "DisplayOrder" : "DisplayOrder",
    "IsHD" : true,
    "EnableMediaSourceDisplay" : true,
    "SeriesThumbImageTag" : "SeriesThumbImageTag",
    "MovieCount" : 4,
    "People" : [ {
      "Role" : "Role",
      "Type" : "Type",
      "PrimaryImageTag" : "PrimaryImageTag",
      "Id" : "Id",
      "Name" : "Name",
      "ImageBlurHashes" : {
        "Art" : {
          "key" : "Art"
        },
        "Banner" : {
          "key" : "Banner"
        },
        "Thumb" : {
          "key" : "Thumb"
        },
        "Chapter" : {
          "key" : "Chapter"
        },
        "BoxRear" : {
          "key" : "BoxRear"
        },
        "Box" : {
          "key" : "Box"
        },
        "Profile" : {
          "key" : "Profile"
        },
        "Logo" : {
          "key" : "Logo"
        },
        "Disc" : {
          "key" : "Disc"
        },
        "Primary" : {
          "key" : "Primary"
        },
        "Screenshot" : {
          "key" : "Screenshot"
        },
        "Backdrop" : {
          "key" : "Backdrop"
        },
        "Menu" : {
          "key" : "Menu"
        }
      }
    }, {
      "Role" : "Role",
      "Type" : "Type",
      "PrimaryImageTag" : "PrimaryImageTag",
      "Id" : "Id",
      "Name" : "Name",
      "ImageBlurHashes" : {
        "Art" : {
          "key" : "Art"
        },
        "Banner" : {
          "key" : "Banner"
        },
        "Thumb" : {
          "key" : "Thumb"
        },
        "Chapter" : {
          "key" : "Chapter"
        },
        "BoxRear" : {
          "key" : "BoxRear"
        },
        "Box" : {
          "key" : "Box"
        },
        "Profile" : {
          "key" : "Profile"
        },
        "Logo" : {
          "key" : "Logo"
        },
        "Disc" : {
          "key" : "Disc"
        },
        "Primary" : {
          "key" : "Primary"
        },
        "Screenshot" : {
          "key" : "Screenshot"
        },
        "Backdrop" : {
          "key" : "Backdrop"
        },
        "Menu" : {
          "key" : "Menu"
        }
      }
    } ],
    "Overview" : "Overview",
    "SpecialFeatureCount" : 3,
    "ImageOrientation" : "",
    "AlbumArtist" : "AlbumArtist",
    "ImageTags" : {
      "key" : "ImageTags"
    },
    "AspectRatio" : "AspectRatio",
    "TrailerCount" : 0,
    "OriginalTitle" : "OriginalTitle",
    "ForcedSortName" : "ForcedSortName",
    "CurrentProgram" : "",
    "LocationType" : "",
    "IsPremiere" : true,
    "Altitude" : 0.8774076871421566
  }, {
    "SeasonName" : "SeasonName",
    "PremiereDate" : "2000-01-23T04:56:07.000+00:00",
    "CriticRating" : 9.018348,
    "AirTime" : "AirTime",
    "Studios" : [ {
      "Id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
      "Name" : "Name"
    }, {
      "Id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
      "Name" : "Name"
    } ],
    "CameraMake" : "CameraMake",
    "Aperture" : 1.041444916118296,
    "ChannelPrimaryImageTag" : "ChannelPrimaryImageTag",
    "ExtraType" : "ExtraType",
    "ParentBackdropItemId" : "ParentBackdropItemId",
    "Etag" : "Etag",
    "ParentLogoImageTag" : "ParentLogoImageTag",
    "ExposureTime" : 6.628464275087742,
    "IsoType" : "",
    "MediaType" : "MediaType",
    "Tags" : [ "Tags", "Tags" ],
    "ImageBlurHashes" : {
      "Art" : {
        "key" : "Art"
      },
      "Banner" : {
        "key" : "Banner"
      },
      "Thumb" : {
        "key" : "Thumb"
      },
      "Chapter" : {
        "key" : "Chapter"
      },
      "BoxRear" : {
        "key" : "BoxRear"
      },
      "Box" : {
        "key" : "Box"
      },
      "Profile" : {
        "key" : "Profile"
      },
      "Logo" : {
        "key" : "Logo"
      },
      "Disc" : {
        "key" : "Disc"
      },
      "Primary" : {
        "key" : "Primary"
      },
      "Screenshot" : {
        "key" : "Screenshot"
      },
      "Backdrop" : {
        "key" : "Backdrop"
      },
      "Menu" : {
        "key" : "Menu"
      }
    },
    "Status" : "Status",
    "IndexNumberEnd" : 6,
    "ArtistItems" : [ null, null ],
    "MediaSources" : [ {
      "EncoderPath" : "EncoderPath",
      "RequiredHttpHeaders" : {
        "key" : "RequiredHttpHeaders"
      },
      "RunTimeTicks" : 5,
      "MediaStreams" : [ {
        "VideoRange" : "VideoRange",
        "CodecTimeBase" : "CodecTimeBase",
        "ColorSpace" : "ColorSpace",
        "Index" : 7,
        "ColorRange" : "ColorRange",
        "localizedForced" : "localizedForced",
        "BitDepth" : 9,
        "Channels" : 4,
        "Profile" : "Profile",
        "SupportsExternalStream" : true,
        "localizedDefault" : "localizedDefault",
        "DeliveryUrl" : "DeliveryUrl",
        "Codec" : "Codec",
        "ColorPrimaries" : "ColorPrimaries",
        "SampleRate" : 7,
        "Language" : "Language",
        "IsTextSubtitleStream" : true,
        "IsAnamorphic" : true,
        "NalLengthSize" : "NalLengthSize",
        "Height" : 1,
        "PixelFormat" : "PixelFormat",
        "RefFrames" : 3,
        "IsAVC" : true,
        "Width" : 1,
        "TimeBase" : "TimeBase",
        "ColorTransfer" : "ColorTransfer",
        "CodecTag" : "CodecTag",
        "IsDefault" : true,
        "Path" : "Path",
        "Comment" : "Comment",
        "DeliveryMethod" : "",
        "IsExternalUrl" : true,
        "DisplayTitle" : "DisplayTitle",
        "IsForced" : true,
        "ChannelLayout" : "ChannelLayout",
        "localizedUndefined" : "localizedUndefined",
        "PacketLength" : 2,
        "Title" : "Title",
        "RealFrameRate" : 6.846853,
        "AspectRatio" : "AspectRatio",
        "AverageFrameRate" : 1.4894159,
        "Type" : "",
        "Score" : 1,
        "IsExternal" : true,
        "IsInterlaced" : true,
        "Level" : 4.965218492984954,
        "BitRate" : 7
      }, {
        "VideoRange" : "VideoRange",
        "CodecTimeBase" : "CodecTimeBase",
        "ColorSpace" : "ColorSpace",
        "Index" : 7,
        "ColorRange" : "ColorRange",
        "localizedForced" : "localizedForced",
        "BitDepth" : 9,
        "Channels" : 4,
        "Profile" : "Profile",
        "SupportsExternalStream" : true,
        "localizedDefault" : "localizedDefault",
        "DeliveryUrl" : "DeliveryUrl",
        "Codec" : "Codec",
        "ColorPrimaries" : "ColorPrimaries",
        "SampleRate" : 7,
        "Language" : "Language",
        "IsTextSubtitleStream" : true,
        "IsAnamorphic" : true,
        "NalLengthSize" : "NalLengthSize",
        "Height" : 1,
        "PixelFormat" : "PixelFormat",
        "RefFrames" : 3,
        "IsAVC" : true,
        "Width" : 1,
        "TimeBase" : "TimeBase",
        "ColorTransfer" : "ColorTransfer",
        "CodecTag" : "CodecTag",
        "IsDefault" : true,
        "Path" : "Path",
        "Comment" : "Comment",
        "DeliveryMethod" : "",
        "IsExternalUrl" : true,
        "DisplayTitle" : "DisplayTitle",
        "IsForced" : true,
        "ChannelLayout" : "ChannelLayout",
        "localizedUndefined" : "localizedUndefined",
        "PacketLength" : 2,
        "Title" : "Title",
        "RealFrameRate" : 6.846853,
        "AspectRatio" : "AspectRatio",
        "AverageFrameRate" : 1.4894159,
        "Type" : "",
        "Score" : 1,
        "IsExternal" : true,
        "IsInterlaced" : true,
        "Level" : 4.965218492984954,
        "BitRate" : 7
      } ],
      "Size" : 5,
      "Video3DFormat" : "",
      "BufferMs" : 2,
      "Timestamp" : "",
      "Name" : "Name",
      "RequiresOpening" : true,
      "SupportsDirectStream" : true,
      "VideoType" : "",
      "RequiresClosing" : true,
      "Container" : "Container",
      "IsoType" : "",
      "LiveStreamId" : "LiveStreamId",
      "RequiresLooping" : true,
      "Protocol" : "",
      "DefaultSubtitleStreamIndex" : 8,
      "GenPtsInput" : true,
      "IsInfiniteStream" : true,
      "Path" : "Path",
      "IsRemote" : true,
      "EncoderProtocol" : "",
      "IgnoreIndex" : true,
      "SupportsDirectPlay" : true,
      "TranscodingSubProtocol" : "TranscodingSubProtocol",
      "Formats" : [ "Formats", "Formats" ],
      "AnalyzeDurationMs" : 9,
      "Bitrate" : 9,
      "OpenToken" : "OpenToken",
      "SupportsProbing" : true,
      "Type" : "",
      "MediaAttachments" : [ {
        "CodecTag" : "CodecTag",
        "Comment" : "Comment",
        "DeliveryUrl" : "DeliveryUrl",
        "Codec" : "Codec",
        "FileName" : "FileName",
        "Index" : 5,
        "MimeType" : "MimeType"
      }, {
        "CodecTag" : "CodecTag",
        "Comment" : "Comment",
        "DeliveryUrl" : "DeliveryUrl",
        "Codec" : "Codec",
        "FileName" : "FileName",
        "Index" : 5,
        "MimeType" : "MimeType"
      } ],
      "ReadAtNativeFramerate" : true,
      "ETag" : "ETag",
      "TranscodingContainer" : "TranscodingContainer",
      "IgnoreDts" : true,
      "TranscodingUrl" : "TranscodingUrl",
      "Id" : "Id",
      "SupportsTranscoding" : true,
      "DefaultAudioStreamIndex" : 6
    }, {
      "EncoderPath" : "EncoderPath",
      "RequiredHttpHeaders" : {
        "key" : "RequiredHttpHeaders"
      },
      "RunTimeTicks" : 5,
      "MediaStreams" : [ {
        "VideoRange" : "VideoRange",
        "CodecTimeBase" : "CodecTimeBase",
        "ColorSpace" : "ColorSpace",
        "Index" : 7,
        "ColorRange" : "ColorRange",
        "localizedForced" : "localizedForced",
        "BitDepth" : 9,
        "Channels" : 4,
        "Profile" : "Profile",
        "SupportsExternalStream" : true,
        "localizedDefault" : "localizedDefault",
        "DeliveryUrl" : "DeliveryUrl",
        "Codec" : "Codec",
        "ColorPrimaries" : "ColorPrimaries",
        "SampleRate" : 7,
        "Language" : "Language",
        "IsTextSubtitleStream" : true,
        "IsAnamorphic" : true,
        "NalLengthSize" : "NalLengthSize",
        "Height" : 1,
        "PixelFormat" : "PixelFormat",
        "RefFrames" : 3,
        "IsAVC" : true,
        "Width" : 1,
        "TimeBase" : "TimeBase",
        "ColorTransfer" : "ColorTransfer",
        "CodecTag" : "CodecTag",
        "IsDefault" : true,
        "Path" : "Path",
        "Comment" : "Comment",
        "DeliveryMethod" : "",
        "IsExternalUrl" : true,
        "DisplayTitle" : "DisplayTitle",
        "IsForced" : true,
        "ChannelLayout" : "ChannelLayout",
        "localizedUndefined" : "localizedUndefined",
        "PacketLength" : 2,
        "Title" : "Title",
        "RealFrameRate" : 6.846853,
        "AspectRatio" : "AspectRatio",
        "AverageFrameRate" : 1.4894159,
        "Type" : "",
        "Score" : 1,
        "IsExternal" : true,
        "IsInterlaced" : true,
        "Level" : 4.965218492984954,
        "BitRate" : 7
      }, {
        "VideoRange" : "VideoRange",
        "CodecTimeBase" : "CodecTimeBase",
        "ColorSpace" : "ColorSpace",
        "Index" : 7,
        "ColorRange" : "ColorRange",
        "localizedForced" : "localizedForced",
        "BitDepth" : 9,
        "Channels" : 4,
        "Profile" : "Profile",
        "SupportsExternalStream" : true,
        "localizedDefault" : "localizedDefault",
        "DeliveryUrl" : "DeliveryUrl",
        "Codec" : "Codec",
        "ColorPrimaries" : "ColorPrimaries",
        "SampleRate" : 7,
        "Language" : "Language",
        "IsTextSubtitleStream" : true,
        "IsAnamorphic" : true,
        "NalLengthSize" : "NalLengthSize",
        "Height" : 1,
        "PixelFormat" : "PixelFormat",
        "RefFrames" : 3,
        "IsAVC" : true,
        "Width" : 1,
        "TimeBase" : "TimeBase",
        "ColorTransfer" : "ColorTransfer",
        "CodecTag" : "CodecTag",
        "IsDefault" : true,
        "Path" : "Path",
        "Comment" : "Comment",
        "DeliveryMethod" : "",
        "IsExternalUrl" : true,
        "DisplayTitle" : "DisplayTitle",
        "IsForced" : true,
        "ChannelLayout" : "ChannelLayout",
        "localizedUndefined" : "localizedUndefined",
        "PacketLength" : 2,
        "Title" : "Title",
        "RealFrameRate" : 6.846853,
        "AspectRatio" : "AspectRatio",
        "AverageFrameRate" : 1.4894159,
        "Type" : "",
        "Score" : 1,
        "IsExternal" : true,
        "IsInterlaced" : true,
        "Level" : 4.965218492984954,
        "BitRate" : 7
      } ],
      "Size" : 5,
      "Video3DFormat" : "",
      "BufferMs" : 2,
      "Timestamp" : "",
      "Name" : "Name",
      "RequiresOpening" : true,
      "SupportsDirectStream" : true,
      "VideoType" : "",
      "RequiresClosing" : true,
      "Container" : "Container",
      "IsoType" : "",
      "LiveStreamId" : "LiveStreamId",
      "RequiresLooping" : true,
      "Protocol" : "",
      "DefaultSubtitleStreamIndex" : 8,
      "GenPtsInput" : true,
      "IsInfiniteStream" : true,
      "Path" : "Path",
      "IsRemote" : true,
      "EncoderProtocol" : "",
      "IgnoreIndex" : true,
      "SupportsDirectPlay" : true,
      "TranscodingSubProtocol" : "TranscodingSubProtocol",
      "Formats" : [ "Formats", "Formats" ],
      "AnalyzeDurationMs" : 9,
      "Bitrate" : 9,
      "OpenToken" : "OpenToken",
      "SupportsProbing" : true,
      "Type" : "",
      "MediaAttachments" : [ {
        "CodecTag" : "CodecTag",
        "Comment" : "Comment",
        "DeliveryUrl" : "DeliveryUrl",
        "Codec" : "Codec",
        "FileName" : "FileName",
        "Index" : 5,
        "MimeType" : "MimeType"
      }, {
        "CodecTag" : "CodecTag",
        "Comment" : "Comment",
        "DeliveryUrl" : "DeliveryUrl",
        "Codec" : "Codec",
        "FileName" : "FileName",
        "Index" : 5,
        "MimeType" : "MimeType"
      } ],
      "ReadAtNativeFramerate" : true,
      "ETag" : "ETag",
      "TranscodingContainer" : "TranscodingContainer",
      "IgnoreDts" : true,
      "TranscodingUrl" : "TranscodingUrl",
      "Id" : "Id",
      "SupportsTranscoding" : true,
      "DefaultAudioStreamIndex" : 6
    } ],
    "GenreItems" : [ null, null ],
    "OfficialRating" : "OfficialRating",
    "ProgramCount" : 7,
    "ProgramId" : "ProgramId",
    "Longitude" : 9.132027271330688,
    "LockData" : true,
    "FocalLength" : 4.258773108174356,
    "IsNews" : true,
    "ShutterSpeed" : 4.678947989005849,
    "Id" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "IsFolder" : true,
    "SeriesTimerId" : "SeriesTimerId",
    "SeriesId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "MediaStreams" : [ null, null ],
    "IsPlaceHolder" : true,
    "CanDownload" : true,
    "SeriesCount" : 8,
    "IsMovie" : true,
    "DateLastMediaAdded" : "2000-01-23T04:56:07.000+00:00",
    "ParentArtImageTag" : "ParentArtImageTag",
    "PlayAccess" : "",
    "SeriesStudio" : "SeriesStudio",
    "IsLive" : true,
    "Width" : 4,
    "ExternalUrls" : [ {
      "Url" : "Url",
      "Name" : "Name"
    }, {
      "Url" : "Url",
      "Name" : "Name"
    } ],
    "RecursiveItemCount" : 6,
    "Path" : "Path",
    "ParentId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "MusicVideoCount" : 3,
    "ScreenshotImageTags" : [ "ScreenshotImageTags", "ScreenshotImageTags" ],
    "EpisodeCount" : 3,
    "IsSeries" : true,
    "ProductionLocations" : [ "ProductionLocations", "ProductionLocations" ],
    "ParentPrimaryImageItemId" : "ParentPrimaryImageItemId",
    "EndDate" : "2000-01-23T04:56:07.000+00:00",
    "SeriesPrimaryImageTag" : "SeriesPrimaryImageTag",
    "ParentThumbItemId" : "ParentThumbItemId",
    "PreferredMetadataLanguage" : "PreferredMetadataLanguage",
    "Type" : "Type",
    "BackdropImageTags" : [ "BackdropImageTags", "BackdropImageTags" ],
    "ParentBackdropImageTags" : [ "ParentBackdropImageTags", "ParentBackdropImageTags" ],
    "AirsBeforeEpisodeNumber" : 1,
    "ChildCount" : 3,
    "Audio" : "",
    "Artists" : [ "Artists", "Artists" ],
    "ChannelType" : "",
    "RunTimeTicks" : 6,
    "AlbumPrimaryImageTag" : "AlbumPrimaryImageTag",
    "Video3DFormat" : "",
    "CumulativeRunTimeTicks" : 3,
    "SourceType" : "SourceType",
    "CanDelete" : true,
    "PlaylistItemId" : "PlaylistItemId",
    "DisplayPreferencesId" : "DisplayPreferencesId",
    "Album" : "Album",
    "Latitude" : 7.260521264802104,
    "SortName" : "SortName",
    "ArtistCount" : 5,
    "Name" : "Name",
    "StartDate" : "2000-01-23T04:56:07.000+00:00",
    "Container" : "Container",
    "ProductionYear" : 1,
    "SeriesName" : "SeriesName",
    "ParentArtItemId" : "ParentArtItemId",
    "AlbumId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "SupportsSync" : true,
    "LocalTrailerCount" : 5,
    "IndexNumber" : 2,
    "CompletionPercentage" : 0.5199002018724985,
    "Genres" : [ "Genres", "Genres" ],
    "SeasonId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "LockedFields" : [ "Cast", "Cast" ],
    "ParentPrimaryImageTag" : "ParentPrimaryImageTag",
    "ProviderIds" : {
      "key" : "ProviderIds"
    },
    "RemoteTrailers" : [ {
      "Url" : "Url",
      "Name" : "Name"
    }, {
      "Url" : "Url",
      "Name" : "Name"
    } ],
    "MediaSourceCount" : 7,
    "CustomRating" : "CustomRating",
    "AirsAfterSeasonNumber" : 6,
    "AirDays" : [ "Sunday", "Sunday" ],
    "ParentLogoItemId" : "ParentLogoItemId",
    "PartCount" : 0,
    "ChannelName" : "ChannelName",
    "EpisodeTitle" : "EpisodeTitle",
    "IsoSpeedRating" : 9,
    "CommunityRating" : 6.4384236,
    "Software" : "Software",
    "Chapters" : [ {
      "StartPositionTicks" : 6,
      "ImageTag" : "ImageTag",
      "ImageDateModified" : "2000-01-23T04:56:07.000+00:00",
      "ImagePath" : "ImagePath",
      "Name" : "Name"
    }, {
      "StartPositionTicks" : 6,
      "ImageTag" : "ImageTag",
      "ImageDateModified" : "2000-01-23T04:56:07.000+00:00",
      "ImagePath" : "ImagePath",
      "Name" : "Name"
    } ],
    "SongCount" : 3,
    "Taglines" : [ "Taglines", "Taglines" ],
    "AirsBeforeSeasonNumber" : 0,
    "PreferredMetadataCountryCode" : "PreferredMetadataCountryCode",
    "CameraModel" : "CameraModel",
    "ChannelNumber" : "ChannelNumber",
    "UserData" : "",
    "TimerId" : "TimerId",
    "DateCreated" : "2000-01-23T04:56:07.000+00:00",
    "HasSubtitles" : true,
    "ParentThumbImageTag" : "ParentThumbImageTag",
    "IsSports" : true,
    "ChannelId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
    "ParentIndexNumber" : 6,
    "VideoType" : "",
    "AlbumArtists" : [ null, null ],
    "ServerId" : "ServerId",
    "Number" : "Number",
    "AlbumCount" : 7,
    "IsRepeat" : true,
    "CollectionType" : "CollectionType",
    "PrimaryImageAspectRatio" : 7.143538047012306,
    "Height" : 0,
    "IsKids" : true,
    "DisplayOrder" : "DisplayOrder",
    "IsHD" : true,
    "EnableMediaSourceDisplay" : true,
    "SeriesThumbImageTag" : "SeriesThumbImageTag",
    "MovieCount" : 4,
    "People" : [ {
      "Role" : "Role",
      "Type" : "Type",
      "PrimaryImageTag" : "PrimaryImageTag",
      "Id" : "Id",
      "Name" : "Name",
      "ImageBlurHashes" : {
        "Art" : {
          "key" : "Art"
        },
        "Banner" : {
          "key" : "Banner"
        },
        "Thumb" : {
          "key" : "Thumb"
        },
        "Chapter" : {
          "key" : "Chapter"
        },
        "BoxRear" : {
          "key" : "BoxRear"
        },
        "Box" : {
          "key" : "Box"
        },
        "Profile" : {
          "key" : "Profile"
        },
        "Logo" : {
          "key" : "Logo"
        },
        "Disc" : {
          "key" : "Disc"
        },
        "Primary" : {
          "key" : "Primary"
        },
        "Screenshot" : {
          "key" : "Screenshot"
        },
        "Backdrop" : {
          "key" : "Backdrop"
        },
        "Menu" : {
          "key" : "Menu"
        }
      }
    }, {
      "Role" : "Role",
      "Type" : "Type",
      "PrimaryImageTag" : "PrimaryImageTag",
      "Id" : "Id",
      "Name" : "Name",
      "ImageBlurHashes" : {
        "Art" : {
          "key" : "Art"
        },
        "Banner" : {
          "key" : "Banner"
        },
        "Thumb" : {
          "key" : "Thumb"
        },
        "Chapter" : {
          "key" : "Chapter"
        },
        "BoxRear" : {
          "key" : "BoxRear"
        },
        "Box" : {
          "key" : "Box"
        },
        "Profile" : {
          "key" : "Profile"
        },
        "Logo" : {
          "key" : "Logo"
        },
        "Disc" : {
          "key" : "Disc"
        },
        "Primary" : {
          "key" : "Primary"
        },
        "Screenshot" : {
          "key" : "Screenshot"
        },
        "Backdrop" : {
          "key" : "Backdrop"
        },
        "Menu" : {
          "key" : "Menu"
        }
      }
    } ],
    "Overview" : "Overview",
    "SpecialFeatureCount" : 3,
    "ImageOrientation" : "",
    "AlbumArtist" : "AlbumArtist",
    "ImageTags" : {
      "key" : "ImageTags"
    },
    "AspectRatio" : "AspectRatio",
    "TrailerCount" : 0,
    "OriginalTitle" : "OriginalTitle",
    "ForcedSortName" : "ForcedSortName",
    "CurrentProgram" : "",
    "LocationType" : "",
    "IsPremiere" : true,
    "Altitude" : 0.8774076871421566
  } ]
}}]
     - parameter playlistId: (path) The playlist id. 
     - parameter userId: (query) User id. 
     - parameter startIndex: (query) Optional. The record index to start at. All items with a lower index will be dropped from the results. (optional)
     - parameter limit: (query) Optional. The maximum number of records to return. (optional)
     - parameter fields: (query) Optional. Specify additional fields of information to return in the output. (optional)
     - parameter enableImages: (query) Optional. Include image information in output. (optional)
     - parameter enableUserData: (query) Optional. Include user data. (optional)
     - parameter imageTypeLimit: (query) Optional. The max number of images to return, per image type. (optional)
     - parameter enableImageTypes: (query) Optional. The image types to include in the output. (optional)

     - returns: RequestBuilder<BaseItemDtoQueryResult> 
     */
    open class func getPlaylistItemsWithRequestBuilder(playlistId: UUID, userId: UUID, startIndex: Int? = nil, limit: Int? = nil, fields: [ItemFields]? = nil, enableImages: Bool? = nil, enableUserData: Bool? = nil, imageTypeLimit: Int? = nil, enableImageTypes: [ImageType]? = nil) -> RequestBuilder<BaseItemDtoQueryResult> {
        var path = "/Playlists/{playlistId}/Items"
        let playlistIdPreEscape = "\(playlistId)"
        let playlistIdPostEscape = playlistIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{playlistId}", with: playlistIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "userId": userId, 
                        "startIndex": startIndex?.encodeToJSON(), 
                        "limit": limit?.encodeToJSON(), 
                        "fields": fields, 
                        "enableImages": enableImages, 
                        "enableUserData": enableUserData, 
                        "imageTypeLimit": imageTypeLimit?.encodeToJSON(), 
                        "enableImageTypes": enableImageTypes
        ])


        let requestBuilder: RequestBuilder<BaseItemDtoQueryResult>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     Moves a playlist item.

     - parameter playlistId: (path) The playlist id. 
     - parameter itemId: (path) The item id. 
     - parameter newIndex: (path) The new index. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func moveItem(playlistId: String, itemId: String, newIndex: Int, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        moveItemWithRequestBuilder(playlistId: playlistId, itemId: itemId, newIndex: newIndex).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Moves a playlist item.
     - POST /Playlists/{playlistId}/Items/{itemId}/Move/{newIndex}
     - 

     - API Key:
       - type: apiKey X-Emby-Authorization 
       - name: CustomAuthentication
     - parameter playlistId: (path) The playlist id. 
     - parameter itemId: (path) The item id. 
     - parameter newIndex: (path) The new index. 

     - returns: RequestBuilder<Void> 
     */
    open class func moveItemWithRequestBuilder(playlistId: String, itemId: String, newIndex: Int) -> RequestBuilder<Void> {
        var path = "/Playlists/{playlistId}/Items/{itemId}/Move/{newIndex}"
        let playlistIdPreEscape = "\(playlistId)"
        let playlistIdPostEscape = playlistIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{playlistId}", with: playlistIdPostEscape, options: .literal, range: nil)
        let itemIdPreEscape = "\(itemId)"
        let itemIdPostEscape = itemIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{itemId}", with: itemIdPostEscape, options: .literal, range: nil)
        let newIndexPreEscape = "\(newIndex)"
        let newIndexPostEscape = newIndexPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{newIndex}", with: newIndexPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     Removes items from a playlist.

     - parameter playlistId: (path) The playlist id. 
     - parameter entryIds: (query) The item ids, comma delimited. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func removeFromPlaylist(playlistId: String, entryIds: [String]? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        removeFromPlaylistWithRequestBuilder(playlistId: playlistId, entryIds: entryIds).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Removes items from a playlist.
     - DELETE /Playlists/{playlistId}/Items
     - 

     - API Key:
       - type: apiKey X-Emby-Authorization 
       - name: CustomAuthentication
     - parameter playlistId: (path) The playlist id. 
     - parameter entryIds: (query) The item ids, comma delimited. (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func removeFromPlaylistWithRequestBuilder(playlistId: String, entryIds: [String]? = nil) -> RequestBuilder<Void> {
        var path = "/Playlists/{playlistId}/Items"
        let playlistIdPreEscape = "\(playlistId)"
        let playlistIdPostEscape = playlistIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{playlistId}", with: playlistIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "entryIds": entryIds
        ])


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
