//
// AllOfObjectGroupUpdateModelType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Gets the update type. */

public struct AllOfObjectGroupUpdateModelType: Codable {




}
