//
// AllOfNotificationDtoLevel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Gets or sets the notification level. */

public struct AllOfNotificationDtoLevel: Codable {




}
