//
// AllOfSendCommandCommand.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Gets the command. */

public struct AllOfSendCommandCommand: Codable {




}
