//
// AllOfSessionInfoFullNowPlayingItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Class BaseItem. */

public struct AllOfSessionInfoFullNowPlayingItem: Codable {

    public var size: Int64?
    public var container: String?
    public var dateLastSaved: Date?
    /** Gets or sets the remote trailers. */
    public var remoteTrailers: [MediaUrl]?
    public var isHD: Bool?
    public var isShortcut: Bool?
    public var shortcutPath: String?
    public var width: Int?
    public var height: Int?
    public var extraIds: [UUID]?
    public var supportsExternalTransfer: Bool?

    public init(size: Int64? = nil, container: String? = nil, dateLastSaved: Date? = nil, remoteTrailers: [MediaUrl]? = nil, isHD: Bool? = nil, isShortcut: Bool? = nil, shortcutPath: String? = nil, width: Int? = nil, height: Int? = nil, extraIds: [UUID]? = nil, supportsExternalTransfer: Bool? = nil) {
        self.size = size
        self.container = container
        self.dateLastSaved = dateLastSaved
        self.remoteTrailers = remoteTrailers
        self.isHD = isHD
        self.isShortcut = isShortcut
        self.shortcutPath = shortcutPath
        self.width = width
        self.height = height
        self.extraIds = extraIds
        self.supportsExternalTransfer = supportsExternalTransfer
    }

    public enum CodingKeys: String, CodingKey { 
        case size = "Size"
        case container = "Container"
        case dateLastSaved = "DateLastSaved"
        case remoteTrailers = "RemoteTrailers"
        case isHD = "IsHD"
        case isShortcut = "IsShortcut"
        case shortcutPath = "ShortcutPath"
        case width = "Width"
        case height = "Height"
        case extraIds = "ExtraIds"
        case supportsExternalTransfer = "SupportsExternalTransfer"
    }

}
