//
// AllOfPluginInfoStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Gets or sets a value indicating the status of the plugin. */

public struct AllOfPluginInfoStatus: Codable {




}
