//
// AllOfTaskInfoState.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Gets or sets the state of the task. */

public struct AllOfTaskInfoState: Codable {




}
