//
// AllOfQueueRequestDtoMode.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Gets or sets the mode in which to add the new items. */

public struct AllOfQueueRequestDtoMode: Codable {




}
