//
// AllOfPlayRequestPlayCommand.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Gets or sets the play command. */

public struct AllOfPlayRequestPlayCommand: Codable {




}
