//
// AllOfBaseItemDtoIsoType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Gets or sets the type of the iso. */

public struct AllOfBaseItemDtoIsoType: Codable {




}
