//
// AllOfConfigurationPageInfoConfigurationPageType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Gets or sets the type of the configuration page. */

public struct AllOfConfigurationPageInfoConfigurationPageType: Codable {




}
