//
// AllOfDisplayPreferencesDtoSortOrder.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An enum representing the sorting order. */

public struct AllOfDisplayPreferencesDtoSortOrder: Codable {




}
