//
// AllOfSystemInfoEncoderLocation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Enum describing the location of the FFmpeg tool. */

public struct AllOfSystemInfoEncoderLocation: Codable {




}
