//
// AllOfSetShuffleModeRequestDtoMode.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Gets or sets the shuffle mode. */

public struct AllOfSetShuffleModeRequestDtoMode: Codable {




}
