//
// AllOfDisplayPreferencesDtoScrollDirection.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An enum representing the axis that should be scrolled. */

public struct AllOfDisplayPreferencesDtoScrollDirection: Codable {




}
