//
// ChannelType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Enum ChannelType. */
public enum ChannelType: String, Codable {
    case tv = "TV"
    case radio = "Radio"
}