//
// CodecProfile.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CodecProfile: Codable {

    public var type: AllOfCodecProfileModelType?
    public var conditions: [ProfileCondition]?
    public var applyConditions: [ProfileCondition]?
    public var codec: String?
    public var container: String?

    public init(type: AllOfCodecProfileModelType? = nil, conditions: [ProfileCondition]? = nil, applyConditions: [ProfileCondition]? = nil, codec: String? = nil, container: String? = nil) {
        self.type = type
        self.conditions = conditions
        self.applyConditions = applyConditions
        self.codec = codec
        self.container = container
    }

    public enum CodingKeys: String, CodingKey { 
        case type = "Type"
        case conditions = "Conditions"
        case applyConditions = "ApplyConditions"
        case codec = "Codec"
        case container = "Container"
    }

}
