//
// CodecType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum CodecType: String, Codable {
    case video = "Video"
    case videoAudio = "VideoAudio"
    case audio = "Audio"
}