//
// CollectionTypeOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum CollectionTypeOptions: String, Codable {
    case movies = "Movies"
    case tvShows = "TvShows"
    case music = "Music"
    case musicVideos = "MusicVideos"
    case homeVideos = "HomeVideos"
    case boxSets = "BoxSets"
    case books = "Books"
    case mixed = "Mixed"
}