//
// CollectionType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The type of the collection. */

public struct CollectionType: Codable {




}
