//
// Command1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The MediaBrowser.Model.Session.PlaystateCommand. */

public struct Command1: Codable {




}
