//
// ConfigurationPageInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The configuration page info. */

public struct ConfigurationPageInfo: Codable {

    /** Gets or sets the name. */
    public var name: String?
    /** Gets or sets a value indicating whether the configurations page is enabled in the main menu. */
    public var enableInMainMenu: Bool?
    /** Gets or sets the menu section. */
    public var menuSection: String?
    /** Gets or sets the menu icon. */
    public var menuIcon: String?
    /** Gets or sets the display name. */
    public var displayName: String?
    /** Gets or sets the type of the configuration page. */
    public var configurationPageType: AllOfConfigurationPageInfoConfigurationPageType?
    /** Gets or sets the plugin id. */
    public var pluginId: UUID?

    public init(name: String? = nil, enableInMainMenu: Bool? = nil, menuSection: String? = nil, menuIcon: String? = nil, displayName: String? = nil, configurationPageType: AllOfConfigurationPageInfoConfigurationPageType? = nil, pluginId: UUID? = nil) {
        self.name = name
        self.enableInMainMenu = enableInMainMenu
        self.menuSection = menuSection
        self.menuIcon = menuIcon
        self.displayName = displayName
        self.configurationPageType = configurationPageType
        self.pluginId = pluginId
    }

    public enum CodingKeys: String, CodingKey { 
        case name = "Name"
        case enableInMainMenu = "EnableInMainMenu"
        case menuSection = "MenuSection"
        case menuIcon = "MenuIcon"
        case displayName = "DisplayName"
        case configurationPageType = "ConfigurationPageType"
        case pluginId = "PluginId"
    }

}
