//
// Context5.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Optional. The MediaBrowser.Model.Dlna.EncodingContext. */

public struct Context5: Codable {




}
