//
// ContainerProfile.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ContainerProfile: Codable {

    public var type: AllOfContainerProfileModelType?
    public var conditions: [ProfileCondition]?
    public var container: String?

    public init(type: AllOfContainerProfileModelType? = nil, conditions: [ProfileCondition]? = nil, container: String? = nil) {
        self.type = type
        self.conditions = conditions
        self.container = container
    }

    public enum CodingKeys: String, CodingKey { 
        case type = "Type"
        case conditions = "Conditions"
        case container = "Container"
    }

}
