//
// CountryInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Class CountryInfo. */

public struct CountryInfo: Codable {

    /** Gets or sets the name. */
    public var name: String?
    /** Gets or sets the display name. */
    public var displayName: String?
    /** Gets or sets the name of the two letter ISO region. */
    public var twoLetterISORegionName: String?
    /** Gets or sets the name of the three letter ISO region. */
    public var threeLetterISORegionName: String?

    public init(name: String? = nil, displayName: String? = nil, twoLetterISORegionName: String? = nil, threeLetterISORegionName: String? = nil) {
        self.name = name
        self.displayName = displayName
        self.twoLetterISORegionName = twoLetterISORegionName
        self.threeLetterISORegionName = threeLetterISORegionName
    }

    public enum CodingKeys: String, CodingKey { 
        case name = "Name"
        case displayName = "DisplayName"
        case twoLetterISORegionName = "TwoLetterISORegionName"
        case threeLetterISORegionName = "ThreeLetterISORegionName"
    }

}
