//
// DefaultDirectoryBrowserInfoDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Default directory browser info. */

public struct DefaultDirectoryBrowserInfoDto: Codable {

    /** Gets or sets the path. */
    public var path: String?

    public init(path: String? = nil) {
        self.path = path
    }

    public enum CodingKeys: String, CodingKey { 
        case path = "Path"
    }

}
