//
// DeviceInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DeviceInfo: Codable {

    public var name: String?
    /** Gets or sets the identifier. */
    public var _id: String?
    /** Gets or sets the last name of the user. */
    public var lastUserName: String?
    /** Gets or sets the name of the application. */
    public var appName: String?
    /** Gets or sets the application version. */
    public var appVersion: String?
    /** Gets or sets the last user identifier. */
    public var lastUserId: UUID?
    /** Gets or sets the date last modified. */
    public var dateLastActivity: Date?
    /** Gets or sets the capabilities. */
    public var capabilities: AllOfDeviceInfoCapabilities?
    public var iconUrl: String?

    public init(name: String? = nil, _id: String? = nil, lastUserName: String? = nil, appName: String? = nil, appVersion: String? = nil, lastUserId: UUID? = nil, dateLastActivity: Date? = nil, capabilities: AllOfDeviceInfoCapabilities? = nil, iconUrl: String? = nil) {
        self.name = name
        self._id = _id
        self.lastUserName = lastUserName
        self.appName = appName
        self.appVersion = appVersion
        self.lastUserId = lastUserId
        self.dateLastActivity = dateLastActivity
        self.capabilities = capabilities
        self.iconUrl = iconUrl
    }

    public enum CodingKeys: String, CodingKey { 
        case name = "Name"
        case _id = "Id"
        case lastUserName = "LastUserName"
        case appName = "AppName"
        case appVersion = "AppVersion"
        case lastUserId = "LastUserId"
        case dateLastActivity = "DateLastActivity"
        case capabilities = "Capabilities"
        case iconUrl = "IconUrl"
    }

}
