//
// EncodingContext.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum EncodingContext: String, Codable {
    case streaming = "Streaming"
    case _static = "Static"
}