//
// EndPointInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EndPointInfo: Codable {

    public var isLocal: Bool?
    public var isInNetwork: Bool?

    public init(isLocal: Bool? = nil, isInNetwork: Bool? = nil) {
        self.isLocal = isLocal
        self.isInNetwork = isInNetwork
    }

    public enum CodingKeys: String, CodingKey { 
        case isLocal = "IsLocal"
        case isInNetwork = "IsInNetwork"
    }

}
