//
// FFmpegLocation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Enum describing the location of the FFmpeg tool. */
public enum FFmpegLocation: String, Codable {
    case notFound = "NotFound"
    case setByArgument = "SetByArgument"
    case custom = "Custom"
    case system = "System"
}