//
// FontFile.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Class FontFile. */

public struct FontFile: Codable {

    /** Gets or sets the name. */
    public var name: String?
    /** Gets or sets the size. */
    public var size: Int64?
    /** Gets or sets the date created. */
    public var dateCreated: Date?
    /** Gets or sets the date modified. */
    public var dateModified: Date?

    public init(name: String? = nil, size: Int64? = nil, dateCreated: Date? = nil, dateModified: Date? = nil) {
        self.name = name
        self.size = size
        self.dateCreated = dateCreated
        self.dateModified = dateModified
    }

    public enum CodingKeys: String, CodingKey { 
        case name = "Name"
        case size = "Size"
        case dateCreated = "DateCreated"
        case dateModified = "DateModified"
    }

}
