//
// Format21.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Determines the output format of the image - original,gif,jpg,png. */

public struct Format21: Codable {




}
