//
// Format8.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Optional. The MediaBrowser.Model.Drawing.ImageFormat of the returned image. */

public struct Format8: Codable {




}
