//
// GeneralCommand.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GeneralCommand: Codable {

    /** This exists simply to identify a set of known commands. */
    public var name: AllOfGeneralCommandName?
    public var controllingUserId: UUID?
    public var arguments: [String:String]?

    public init(name: AllOfGeneralCommandName? = nil, controllingUserId: UUID? = nil, arguments: [String:String]? = nil) {
        self.name = name
        self.controllingUserId = controllingUserId
        self.arguments = arguments
    }

    public enum CodingKeys: String, CodingKey { 
        case name = "Name"
        case controllingUserId = "ControllingUserId"
        case arguments = "Arguments"
    }

}
