//
// GroupUpdateType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Enum GroupUpdateType. */
public enum GroupUpdateType: String, Codable {
    case userJoined = "UserJoined"
    case userLeft = "UserLeft"
    case groupJoined = "GroupJoined"
    case groupLeft = "GroupLeft"
    case stateUpdate = "StateUpdate"
    case playQueue = "PlayQueue"
    case notInGroup = "NotInGroup"
    case groupDoesNotExist = "GroupDoesNotExist"
    case createGroupDenied = "CreateGroupDenied"
    case joinGroupDenied = "JoinGroupDenied"
    case libraryAccessDenied = "LibraryAccessDenied"
}