//
// GroupQueueMode.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Enum GroupQueueMode. */
public enum GroupQueueMode: String, Codable {
    case queue = "Queue"
    case queueNext = "QueueNext"
}