//
// HeaderMatchType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum HeaderMatchType: String, Codable {
    case equals = "Equals"
    case regex = "Regex"
    case substring = "Substring"
}