//
// IgnoreWaitRequestDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Class IgnoreWaitRequestDto. */

public struct IgnoreWaitRequestDto: Codable {

    /** Gets or sets a value indicating whether the client should be ignored. */
    public var ignoreWait: Bool?

    public init(ignoreWait: Bool? = nil) {
        self.ignoreWait = ignoreWait
    }

    public enum CodingKeys: String, CodingKey { 
        case ignoreWait = "IgnoreWait"
    }

}
