//
// ImageFormat.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Enum ImageOutputFormat. */
public enum ImageFormat: String, Codable {
    case bmp = "Bmp"
    case gif = "Gif"
    case jpg = "Jpg"
    case png = "Png"
    case webp = "Webp"
}