//
// ImageByNameInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ImageByNameInfo: Codable {

    /** Gets or sets the name. */
    public var name: String?
    /** Gets or sets the theme. */
    public var theme: String?
    /** Gets or sets the context. */
    public var context: String?
    /** Gets or sets the length of the file. */
    public var fileLength: Int64?
    /** Gets or sets the format. */
    public var format: String?

    public init(name: String? = nil, theme: String? = nil, context: String? = nil, fileLength: Int64? = nil, format: String? = nil) {
        self.name = name
        self.theme = theme
        self.context = context
        self.fileLength = fileLength
        self.format = format
    }

    public enum CodingKeys: String, CodingKey { 
        case name = "Name"
        case theme = "Theme"
        case context = "Context"
        case fileLength = "FileLength"
        case format = "Format"
    }

}
