//
// ImageSavingConvention.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum ImageSavingConvention: String, Codable {
    case legacy = "Legacy"
    case compatible = "Compatible"
}