//
// ImageOption.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ImageOption: Codable {

    /** Gets or sets the type. */
    public var type: AllOfImageOptionModelType?
    /** Gets or sets the limit. */
    public var limit: Int?
    /** Gets or sets the minimum width. */
    public var minWidth: Int?

    public init(type: AllOfImageOptionModelType? = nil, limit: Int? = nil, minWidth: Int? = nil) {
        self.type = type
        self.limit = limit
        self.minWidth = minWidth
    }

    public enum CodingKeys: String, CodingKey { 
        case type = "Type"
        case limit = "Limit"
        case minWidth = "MinWidth"
    }

}
