//
// ImageOrientation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum ImageOrientation: String, Codable {
    case topLeft = "TopLeft"
    case topRight = "TopRight"
    case bottomRight = "BottomRight"
    case bottomLeft = "BottomLeft"
    case leftTop = "LeftTop"
    case rightTop = "RightTop"
    case rightBottom = "RightBottom"
    case leftBottom = "LeftBottom"
}