//
// ImageRefreshMode.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** (Optional) Specifies the image refresh mode. */

public struct ImageRefreshMode: Codable {




}
