//
// ImageType32.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** (Unused) Image type. */

public struct ImageType32: Codable {




}
