//
// IPlugin.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Defines the MediaBrowser.Common.Plugins.IPlugin. */

public struct IPlugin: Codable {

    /** Gets the name of the plugin. */
    public var name: String?
    /** Gets the Description. */
    public var _description: String?
    /** Gets the unique id. */
    public var _id: UUID?
    /** Gets the plugin version. */
    public var version: AllOfIPluginVersion?
    /** Gets the path to the assembly file. */
    public var assemblyFilePath: String?
    /** Gets a value indicating whether the plugin can be uninstalled. */
    public var canUninstall: Bool?
    /** Gets the full path to the data folder, where the plugin can store any miscellaneous files needed. */
    public var dataFolderPath: String?

    public init(name: String? = nil, _description: String? = nil, _id: UUID? = nil, version: AllOfIPluginVersion? = nil, assemblyFilePath: String? = nil, canUninstall: Bool? = nil, dataFolderPath: String? = nil) {
        self.name = name
        self._description = _description
        self._id = _id
        self.version = version
        self.assemblyFilePath = assemblyFilePath
        self.canUninstall = canUninstall
        self.dataFolderPath = dataFolderPath
    }

    public enum CodingKeys: String, CodingKey { 
        case name = "Name"
        case _description = "Description"
        case _id = "Id"
        case version = "Version"
        case assemblyFilePath = "AssemblyFilePath"
        case canUninstall = "CanUninstall"
        case dataFolderPath = "DataFolderPath"
    }

}
