//
// IsoType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Enum IsoType. */
public enum IsoType: String, Codable {
    case dvd = "Dvd"
    case bluRay = "BluRay"
}