//
// KeepUntil.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum KeepUntil: String, Codable {
    case untilDeleted = "UntilDeleted"
    case untilSpaceNeeded = "UntilSpaceNeeded"
    case untilWatched = "UntilWatched"
    case untilDate = "UntilDate"
}