//
// LibraryOptionInfoDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Library option info dto. */

public struct LibraryOptionInfoDto: Codable {

    /** Gets or sets name. */
    public var name: String?
    /** Gets or sets a value indicating whether default enabled. */
    public var defaultEnabled: Bool?

    public init(name: String? = nil, defaultEnabled: Bool? = nil) {
        self.name = name
        self.defaultEnabled = defaultEnabled
    }

    public enum CodingKeys: String, CodingKey { 
        case name = "Name"
        case defaultEnabled = "DefaultEnabled"
    }

}
