//
// LiveTvServiceStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum LiveTvServiceStatus: String, Codable {
    case ok = "Ok"
    case unavailable = "Unavailable"
}