//
// LiveStreamResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LiveStreamResponse: Codable {

    public var mediaSource: AllOfLiveStreamResponseMediaSource?

    public init(mediaSource: AllOfLiveStreamResponseMediaSource? = nil) {
        self.mediaSource = mediaSource
    }

    public enum CodingKeys: String, CodingKey { 
        case mediaSource = "MediaSource"
    }

}
