//
// LiveTvChannelMappingsBody1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The set channel mapping dto. */

public struct LiveTvChannelMappingsBody1: Codable {

    /** Gets or sets the provider id. */
    public var providerId: String
    /** Gets or sets the tuner channel id. */
    public var tunerChannelId: String
    /** Gets or sets the provider channel id. */
    public var providerChannelId: String

    public init(providerId: String, tunerChannelId: String, providerChannelId: String) {
        self.providerId = providerId
        self.tunerChannelId = tunerChannelId
        self.providerChannelId = providerChannelId
    }

    public enum CodingKeys: String, CodingKey { 
        case providerId = "ProviderId"
        case tunerChannelId = "TunerChannelId"
        case providerChannelId = "ProviderChannelId"
    }

}
