//
// LocationType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Enum LocationType. */
public enum LocationType: String, Codable {
    case fileSystem = "FileSystem"
    case remote = "Remote"
    case virtual = "Virtual"
    case offline = "Offline"
}