//
// LogFile.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LogFile: Codable {

    /** Gets or sets the date created. */
    public var dateCreated: Date?
    /** Gets or sets the date modified. */
    public var dateModified: Date?
    /** Gets or sets the size. */
    public var size: Int64?
    /** Gets or sets the name. */
    public var name: String?

    public init(dateCreated: Date? = nil, dateModified: Date? = nil, size: Int64? = nil, name: String? = nil) {
        self.dateCreated = dateCreated
        self.dateModified = dateModified
        self.size = size
        self.name = name
    }

    public enum CodingKeys: String, CodingKey { 
        case dateCreated = "DateCreated"
        case dateModified = "DateModified"
        case size = "Size"
        case name = "Name"
    }

}
