//
// MediaSourceType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum MediaSourceType: String, Codable {
    case _default = "Default"
    case grouping = "Grouping"
    case placeholder = "Placeholder"
}