//
// MediaUpdateInfoPathDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The media update info path. */

public struct MediaUpdateInfoPathDto: Codable {

    /** Gets or sets media path. */
    public var path: String?
    /** Gets or sets media update type.  Created, Modified, Deleted. */
    public var updateType: String?

    public init(path: String? = nil, updateType: String? = nil) {
        self.path = path
        self.updateType = updateType
    }

    public enum CodingKeys: String, CodingKey { 
        case path = "Path"
        case updateType = "UpdateType"
    }

}
