//
// MetadataRefreshMode.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** (Optional) Specifies the metadata refresh mode. */

public struct MetadataRefreshMode: Codable {




}
