//
// MetadataOptions.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Class MetadataOptions. */

public struct MetadataOptions: Codable {

    public var itemType: String?
    public var disabledMetadataSavers: [String]?
    public var localMetadataReaderOrder: [String]?
    public var disabledMetadataFetchers: [String]?
    public var metadataFetcherOrder: [String]?
    public var disabledImageFetchers: [String]?
    public var imageFetcherOrder: [String]?

    public init(itemType: String? = nil, disabledMetadataSavers: [String]? = nil, localMetadataReaderOrder: [String]? = nil, disabledMetadataFetchers: [String]? = nil, metadataFetcherOrder: [String]? = nil, disabledImageFetchers: [String]? = nil, imageFetcherOrder: [String]? = nil) {
        self.itemType = itemType
        self.disabledMetadataSavers = disabledMetadataSavers
        self.localMetadataReaderOrder = localMetadataReaderOrder
        self.disabledMetadataFetchers = disabledMetadataFetchers
        self.metadataFetcherOrder = metadataFetcherOrder
        self.disabledImageFetchers = disabledImageFetchers
        self.imageFetcherOrder = imageFetcherOrder
    }

    public enum CodingKeys: String, CodingKey { 
        case itemType = "ItemType"
        case disabledMetadataSavers = "DisabledMetadataSavers"
        case localMetadataReaderOrder = "LocalMetadataReaderOrder"
        case disabledMetadataFetchers = "DisabledMetadataFetchers"
        case metadataFetcherOrder = "MetadataFetcherOrder"
        case disabledImageFetchers = "DisabledImageFetchers"
        case imageFetcherOrder = "ImageFetcherOrder"
    }

}
