//
// ModelType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Optional. Filter by channel type. */

public struct ModelType: Codable {




}
