//
// MovePlaylistItemRequestDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Class MovePlaylistItemRequestDto. */

public struct MovePlaylistItemRequestDto: Codable {

    /** Gets or sets the playlist identifier of the item. */
    public var playlistItemId: UUID?
    /** Gets or sets the new position. */
    public var newIndex: Int?

    public init(playlistItemId: UUID? = nil, newIndex: Int? = nil) {
        self.playlistItemId = playlistItemId
        self.newIndex = newIndex
    }

    public enum CodingKeys: String, CodingKey { 
        case playlistItemId = "PlaylistItemId"
        case newIndex = "NewIndex"
    }

}
