//
// NameValuePair.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NameValuePair: Codable {

    /** Gets or sets the name. */
    public var name: String?
    /** Gets or sets the value. */
    public var value: String?

    public init(name: String? = nil, value: String? = nil) {
        self.name = name
        self.value = value
    }

    public enum CodingKeys: String, CodingKey { 
        case name = "Name"
        case value = "Value"
    }

}
