//
// NameGuidPair.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NameGuidPair: Codable {

    public var name: String?
    public var _id: UUID?

    public init(name: String? = nil, _id: UUID? = nil) {
        self.name = name
        self._id = _id
    }

    public enum CodingKeys: String, CodingKey { 
        case name = "Name"
        case _id = "Id"
    }

}
