//
// NotificationDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The notification DTO. */

public struct NotificationDto: Codable {

    /** Gets or sets the notification ID. Defaults to an empty string. */
    public var _id: String?
    /** Gets or sets the notification&#x27;s user ID. Defaults to an empty string. */
    public var userId: String?
    /** Gets or sets the notification date. */
    public var date: Date?
    /** Gets or sets a value indicating whether the notification has been read. Defaults to false. */
    public var isRead: Bool?
    /** Gets or sets the notification&#x27;s name. Defaults to an empty string. */
    public var name: String?
    /** Gets or sets the notification&#x27;s description. Defaults to an empty string. */
    public var _description: String?
    /** Gets or sets the notification&#x27;s URL. Defaults to an empty string. */
    public var url: String?
    /** Gets or sets the notification level. */
    public var level: AllOfNotificationDtoLevel?

    public init(_id: String? = nil, userId: String? = nil, date: Date? = nil, isRead: Bool? = nil, name: String? = nil, _description: String? = nil, url: String? = nil, level: AllOfNotificationDtoLevel? = nil) {
        self._id = _id
        self.userId = userId
        self.date = date
        self.isRead = isRead
        self.name = name
        self._description = _description
        self.url = url
        self.level = level
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "Id"
        case userId = "UserId"
        case date = "Date"
        case isRead = "IsRead"
        case name = "Name"
        case _description = "Description"
        case url = "Url"
        case level = "Level"
    }

}
