//
// NotificationsSummaryDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The notification summary DTO. */

public struct NotificationsSummaryDto: Codable {

    /** Gets or sets the number of unread notifications. */
    public var unreadCount: Int?
    /** Gets or sets the maximum unread notification level. */
    public var maxUnreadNotificationLevel: AllOfNotificationsSummaryDtoMaxUnreadNotificationLevel?

    public init(unreadCount: Int? = nil, maxUnreadNotificationLevel: AllOfNotificationsSummaryDtoMaxUnreadNotificationLevel? = nil) {
        self.unreadCount = unreadCount
        self.maxUnreadNotificationLevel = maxUnreadNotificationLevel
    }

    public enum CodingKeys: String, CodingKey { 
        case unreadCount = "UnreadCount"
        case maxUnreadNotificationLevel = "MaxUnreadNotificationLevel"
    }

}
