//
// PathSubstitution.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Defines the MediaBrowser.Model.Configuration.PathSubstitution. */

public struct PathSubstitution: Codable {

    /** Gets or sets the value to substitute. */
    public var from: String?
    /** Gets or sets the value to substitution with. */
    public var to: String?

    public init(from: String? = nil, to: String? = nil) {
        self.from = from
        self.to = to
    }

    public enum CodingKeys: String, CodingKey { 
        case from = "From"
        case to = "To"
    }

}
