//
// PlayerStateInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PlayerStateInfo: Codable {

    /** Gets or sets the now playing position ticks. */
    public var positionTicks: Int64?
    /** Gets or sets a value indicating whether this instance can seek. */
    public var canSeek: Bool?
    /** Gets or sets a value indicating whether this instance is paused. */
    public var isPaused: Bool?
    /** Gets or sets a value indicating whether this instance is muted. */
    public var isMuted: Bool?
    /** Gets or sets the volume level. */
    public var volumeLevel: Int?
    /** Gets or sets the index of the now playing audio stream. */
    public var audioStreamIndex: Int?
    /** Gets or sets the index of the now playing subtitle stream. */
    public var subtitleStreamIndex: Int?
    /** Gets or sets the now playing media version identifier. */
    public var mediaSourceId: String?
    /** Gets or sets the play method. */
    public var playMethod: AllOfPlayerStateInfoPlayMethod?
    /** Gets or sets the repeat mode. */
    public var repeatMode: AllOfPlayerStateInfoRepeatMode?

    public init(positionTicks: Int64? = nil, canSeek: Bool? = nil, isPaused: Bool? = nil, isMuted: Bool? = nil, volumeLevel: Int? = nil, audioStreamIndex: Int? = nil, subtitleStreamIndex: Int? = nil, mediaSourceId: String? = nil, playMethod: AllOfPlayerStateInfoPlayMethod? = nil, repeatMode: AllOfPlayerStateInfoRepeatMode? = nil) {
        self.positionTicks = positionTicks
        self.canSeek = canSeek
        self.isPaused = isPaused
        self.isMuted = isMuted
        self.volumeLevel = volumeLevel
        self.audioStreamIndex = audioStreamIndex
        self.subtitleStreamIndex = subtitleStreamIndex
        self.mediaSourceId = mediaSourceId
        self.playMethod = playMethod
        self.repeatMode = repeatMode
    }

    public enum CodingKeys: String, CodingKey { 
        case positionTicks = "PositionTicks"
        case canSeek = "CanSeek"
        case isPaused = "IsPaused"
        case isMuted = "IsMuted"
        case volumeLevel = "VolumeLevel"
        case audioStreamIndex = "AudioStreamIndex"
        case subtitleStreamIndex = "SubtitleStreamIndex"
        case mediaSourceId = "MediaSourceId"
        case playMethod = "PlayMethod"
        case repeatMode = "RepeatMode"
    }

}
