//
// PlayRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Class PlayRequest. */

public struct PlayRequest: Codable {

    /** Gets or sets the item ids. */
    public var itemIds: [UUID]?
    /** Gets or sets the start position ticks that the first item should be played at. */
    public var startPositionTicks: Int64?
    /** Gets or sets the play command. */
    public var playCommand: AllOfPlayRequestPlayCommand?
    /** Gets or sets the controlling user identifier. */
    public var controllingUserId: UUID?
    public var subtitleStreamIndex: Int?
    public var audioStreamIndex: Int?
    public var mediaSourceId: String?
    public var startIndex: Int?

    public init(itemIds: [UUID]? = nil, startPositionTicks: Int64? = nil, playCommand: AllOfPlayRequestPlayCommand? = nil, controllingUserId: UUID? = nil, subtitleStreamIndex: Int? = nil, audioStreamIndex: Int? = nil, mediaSourceId: String? = nil, startIndex: Int? = nil) {
        self.itemIds = itemIds
        self.startPositionTicks = startPositionTicks
        self.playCommand = playCommand
        self.controllingUserId = controllingUserId
        self.subtitleStreamIndex = subtitleStreamIndex
        self.audioStreamIndex = audioStreamIndex
        self.mediaSourceId = mediaSourceId
        self.startIndex = startIndex
    }

    public enum CodingKeys: String, CodingKey { 
        case itemIds = "ItemIds"
        case startPositionTicks = "StartPositionTicks"
        case playCommand = "PlayCommand"
        case controllingUserId = "ControllingUserId"
        case subtitleStreamIndex = "SubtitleStreamIndex"
        case audioStreamIndex = "AudioStreamIndex"
        case mediaSourceId = "MediaSourceId"
        case startIndex = "StartIndex"
    }

}
