//
// PlaybackInfoResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Class PlaybackInfoResponse. */

public struct PlaybackInfoResponse: Codable {

    /** Gets or sets the media sources. */
    public var mediaSources: [MediaSourceInfo]?
    /** Gets or sets the play session identifier. */
    public var playSessionId: String?
    /** Gets or sets the error code. */
    public var errorCode: AllOfPlaybackInfoResponseErrorCode?

    public init(mediaSources: [MediaSourceInfo]? = nil, playSessionId: String? = nil, errorCode: AllOfPlaybackInfoResponseErrorCode? = nil) {
        self.mediaSources = mediaSources
        self.playSessionId = playSessionId
        self.errorCode = errorCode
    }

    public enum CodingKeys: String, CodingKey { 
        case mediaSources = "MediaSources"
        case playSessionId = "PlaySessionId"
        case errorCode = "ErrorCode"
    }

}
