//
// PlaylistCreationResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PlaylistCreationResult: Codable {

    public var _id: String?

    public init(_id: String? = nil) {
        self._id = _id
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "Id"
    }

}
