//
// PluginInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** This is a serializable stub class that is used by the api to provide information about installed plugins. */

public struct PluginInfo: Codable {

    /** Gets or sets the name. */
    public var name: String?
    /** Gets or sets the version. */
    public var version: AllOfPluginInfoVersion?
    /** Gets or sets the name of the configuration file. */
    public var configurationFileName: String?
    /** Gets or sets the description. */
    public var _description: String?
    /** Gets or sets the unique id. */
    public var _id: UUID?
    /** Gets or sets a value indicating whether the plugin can be uninstalled. */
    public var canUninstall: Bool?
    /** Gets or sets a value indicating whether this plugin has a valid image. */
    public var hasImage: Bool?
    /** Gets or sets a value indicating the status of the plugin. */
    public var status: AllOfPluginInfoStatus?

    public init(name: String? = nil, version: AllOfPluginInfoVersion? = nil, configurationFileName: String? = nil, _description: String? = nil, _id: UUID? = nil, canUninstall: Bool? = nil, hasImage: Bool? = nil, status: AllOfPluginInfoStatus? = nil) {
        self.name = name
        self.version = version
        self.configurationFileName = configurationFileName
        self._description = _description
        self._id = _id
        self.canUninstall = canUninstall
        self.hasImage = hasImage
        self.status = status
    }

    public enum CodingKeys: String, CodingKey { 
        case name = "Name"
        case version = "Version"
        case configurationFileName = "ConfigurationFileName"
        case _description = "Description"
        case _id = "Id"
        case canUninstall = "CanUninstall"
        case hasImage = "HasImage"
        case status = "Status"
    }

}
