//
// ProfileCondition.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ProfileCondition: Codable {

    public var condition: AllOfProfileConditionCondition?
    public var property: AllOfProfileConditionProperty?
    public var value: String?
    public var isRequired: Bool?

    public init(condition: AllOfProfileConditionCondition? = nil, property: AllOfProfileConditionProperty? = nil, value: String? = nil, isRequired: Bool? = nil) {
        self.condition = condition
        self.property = property
        self.value = value
        self.isRequired = isRequired
    }

    public enum CodingKeys: String, CodingKey { 
        case condition = "Condition"
        case property = "Property"
        case value = "Value"
        case isRequired = "IsRequired"
    }

}
