//
// PublicSystemInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PublicSystemInfo: Codable {

    /** Gets or sets the local address. */
    public var localAddress: String?
    /** Gets or sets the name of the server. */
    public var serverName: String?
    /** Gets or sets the server version. */
    public var version: String?
    /** Gets or sets the product name. This is the AssemblyProduct name. */
    public var productName: String?
    /** Gets or sets the operating system. */
    public var operatingSystem: String?
    /** Gets or sets the id. */
    public var _id: String?
    /** Gets or sets a value indicating whether the startup wizard is completed. */
    public var startupWizardCompleted: Bool?

    public init(localAddress: String? = nil, serverName: String? = nil, version: String? = nil, productName: String? = nil, operatingSystem: String? = nil, _id: String? = nil, startupWizardCompleted: Bool? = nil) {
        self.localAddress = localAddress
        self.serverName = serverName
        self.version = version
        self.productName = productName
        self.operatingSystem = operatingSystem
        self._id = _id
        self.startupWizardCompleted = startupWizardCompleted
    }

    public enum CodingKeys: String, CodingKey { 
        case localAddress = "LocalAddress"
        case serverName = "ServerName"
        case version = "Version"
        case productName = "ProductName"
        case operatingSystem = "OperatingSystem"
        case _id = "Id"
        case startupWizardCompleted = "StartupWizardCompleted"
    }

}
