//
// QueryFiltersLegacy.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct QueryFiltersLegacy: Codable {

    public var genres: [String]?
    public var tags: [String]?
    public var officialRatings: [String]?
    public var years: [Int]?

    public init(genres: [String]? = nil, tags: [String]? = nil, officialRatings: [String]? = nil, years: [Int]? = nil) {
        self.genres = genres
        self.tags = tags
        self.officialRatings = officialRatings
        self.years = years
    }

    public enum CodingKeys: String, CodingKey { 
        case genres = "Genres"
        case tags = "Tags"
        case officialRatings = "OfficialRatings"
        case years = "Years"
    }

}
