//
// QueueRequestDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Class QueueRequestDto. */

public struct QueueRequestDto: Codable {

    /** Gets or sets the items to enqueue. */
    public var itemIds: [UUID]?
    /** Gets or sets the mode in which to add the new items. */
    public var mode: AllOfQueueRequestDtoMode?

    public init(itemIds: [UUID]? = nil, mode: AllOfQueueRequestDtoMode? = nil) {
        self.itemIds = itemIds
        self.mode = mode
    }

    public enum CodingKeys: String, CodingKey { 
        case itemIds = "ItemIds"
        case mode = "Mode"
    }

}
