//
// RecommendationType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum RecommendationType: String, Codable {
    case similarToRecentlyPlayed = "SimilarToRecentlyPlayed"
    case similarToLikedItem = "SimilarToLikedItem"
    case hasDirectorFromRecentlyPlayed = "HasDirectorFromRecentlyPlayed"
    case hasActorFromRecentlyPlayed = "HasActorFromRecentlyPlayed"
    case hasLikedDirector = "HasLikedDirector"
    case hasLikedActor = "HasLikedActor"
}