//
// RecordingStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum RecordingStatus: String, Codable {
    case new = "New"
    case inProgress = "InProgress"
    case completed = "Completed"
    case cancelled = "Cancelled"
    case conflictedOk = "ConflictedOk"
    case conflictedNotOk = "ConflictedNotOk"
    case error = "Error"
}