//
// RemoteImageResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Class RemoteImageResult. */

public struct RemoteImageResult: Codable {

    /** Gets or sets the images. */
    public var images: [RemoteImageInfo]?
    /** Gets or sets the total record count. */
    public var totalRecordCount: Int?
    /** Gets or sets the providers. */
    public var providers: [String]?

    public init(images: [RemoteImageInfo]? = nil, totalRecordCount: Int? = nil, providers: [String]? = nil) {
        self.images = images
        self.totalRecordCount = totalRecordCount
        self.providers = providers
    }

    public enum CodingKeys: String, CodingKey { 
        case images = "Images"
        case totalRecordCount = "TotalRecordCount"
        case providers = "Providers"
    }

}
