//
// SearchHintResult.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Class SearchHintResult. */

public struct SearchHintResult: Codable {

    /** Gets or sets the search hints. */
    public var searchHints: [SearchHint]?
    /** Gets or sets the total record count. */
    public var totalRecordCount: Int?

    public init(searchHints: [SearchHint]? = nil, totalRecordCount: Int? = nil) {
        self.searchHints = searchHints
        self.totalRecordCount = totalRecordCount
    }

    public enum CodingKeys: String, CodingKey { 
        case searchHints = "SearchHints"
        case totalRecordCount = "TotalRecordCount"
    }

}
