//
// SeriesStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Enum SeriesStatus. */
public enum SeriesStatus: String, Codable {
    case continuing = "Continuing"
    case ended = "Ended"
}