//
// ServerDiscoveryInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ServerDiscoveryInfo: Codable {

    /** Gets or sets the address. */
    public var address: String?
    /** Gets or sets the server identifier. */
    public var _id: String?
    /** Gets or sets the name. */
    public var name: String?
    /** Gets or sets the endpoint address. */
    public var endpointAddress: String?

    public init(address: String? = nil, _id: String? = nil, name: String? = nil, endpointAddress: String? = nil) {
        self.address = address
        self._id = _id
        self.name = name
        self.endpointAddress = endpointAddress
    }

    public enum CodingKeys: String, CodingKey { 
        case address = "Address"
        case _id = "Id"
        case name = "Name"
        case endpointAddress = "EndpointAddress"
    }

}
