//
// SetRepeatModeRequestDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Class SetRepeatModeRequestDto. */

public struct SetRepeatModeRequestDto: Codable {

    /** Gets or sets the repeat mode. */
    public var mode: AllOfSetRepeatModeRequestDtoMode?

    public init(mode: AllOfSetRepeatModeRequestDtoMode? = nil) {
        self.mode = mode
    }

    public enum CodingKeys: String, CodingKey { 
        case mode = "Mode"
    }

}
