//
// SortOrder1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Optional. Sort in Ascending or Descending order. */

public struct SortOrder1: Codable {




}
