//
// SpecialViewOptionDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Special view option dto. */

public struct SpecialViewOptionDto: Codable {

    /** Gets or sets view option name. */
    public var name: String?
    /** Gets or sets view option id. */
    public var _id: String?

    public init(name: String? = nil, _id: String? = nil) {
        self.name = name
        self._id = _id
    }

    public enum CodingKeys: String, CodingKey { 
        case name = "Name"
        case _id = "Id"
    }

}
