//
// StartupRemoteAccessBody2.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The startup remote access dto. */

public struct StartupRemoteAccessBody2: Codable {

    /** Gets or sets a value indicating whether enable remote access. */
    public var enableRemoteAccess: Bool
    /** Gets or sets a value indicating whether enable automatic port mapping. */
    public var enableAutomaticPortMapping: Bool

    public init(enableRemoteAccess: Bool, enableAutomaticPortMapping: Bool) {
        self.enableRemoteAccess = enableRemoteAccess
        self.enableAutomaticPortMapping = enableAutomaticPortMapping
    }

    public enum CodingKeys: String, CodingKey { 
        case enableRemoteAccess = "EnableRemoteAccess"
        case enableAutomaticPortMapping = "EnableAutomaticPortMapping"
    }

}
