//
// StartupUserBody1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The DTO containing username and password. */

public struct StartupUserBody1: Codable {

    /** Gets or sets the username. */
    public var name: String?
    /** Gets or sets the user&#x27;s password. */
    public var password: String?

    public init(name: String? = nil, password: String? = nil) {
        self.name = name
        self.password = password
    }

    public enum CodingKeys: String, CodingKey { 
        case name = "Name"
        case password = "Password"
    }

}
