//
// SubtitleMethod12.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Optional. Specify the subtitle delivery method. */

public struct SubtitleMethod12: Codable {




}
