//
// SubtitleMethod8.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Optional. Specify the subtitle delivery method. */

public struct SubtitleMethod8: Codable {




}
