//
// SyncPlayJoinBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The group to join. */

public struct SyncPlayJoinBody: Codable {

    /** Gets or sets the group identifier. */
    public var groupId: UUID?

    public init(groupId: UUID? = nil) {
        self.groupId = groupId
    }

    public enum CodingKeys: String, CodingKey { 
        case groupId = "GroupId"
    }

}
