//
// SyncPlayUserAccessType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Enum SyncPlayUserAccessType. */
public enum SyncPlayUserAccessType: String, Codable {
    case createAndJoinGroups = "CreateAndJoinGroups"
    case joinGroups = "JoinGroups"
    case _none = "None"
}