//
// SyncPlaySetShuffleModeBody1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The new shuffle mode. */

public struct SyncPlaySetShuffleModeBody1: Codable {

    /** Gets or sets the shuffle mode. */
    public var mode: Any?

    public init(mode: Any? = nil) {
        self.mode = mode
    }

    public enum CodingKeys: String, CodingKey { 
        case mode = "Mode"
    }

}
