//
// SyncPlaySetRepeatModeBody2.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The new repeat mode. */

public struct SyncPlaySetRepeatModeBody2: Codable {

    /** Gets or sets the repeat mode. */
    public var mode: Any?

    public init(mode: Any? = nil) {
        self.mode = mode
    }

    public enum CodingKeys: String, CodingKey { 
        case mode = "Mode"
    }

}
