//
// TaskTriggerInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Class TaskTriggerInfo. */

public struct TaskTriggerInfo: Codable {

    /** Gets or sets the type. */
    public var type: String?
    /** Gets or sets the time of day. */
    public var timeOfDayTicks: Int64?
    /** Gets or sets the interval. */
    public var intervalTicks: Int64?
    /** Gets or sets the day of week. */
    public var dayOfWeek: AllOfTaskTriggerInfoDayOfWeek?
    /** Gets or sets the maximum runtime ticks. */
    public var maxRuntimeTicks: Int64?

    public init(type: String? = nil, timeOfDayTicks: Int64? = nil, intervalTicks: Int64? = nil, dayOfWeek: AllOfTaskTriggerInfoDayOfWeek? = nil, maxRuntimeTicks: Int64? = nil) {
        self.type = type
        self.timeOfDayTicks = timeOfDayTicks
        self.intervalTicks = intervalTicks
        self.dayOfWeek = dayOfWeek
        self.maxRuntimeTicks = maxRuntimeTicks
    }

    public enum CodingKeys: String, CodingKey { 
        case type = "Type"
        case timeOfDayTicks = "TimeOfDayTicks"
        case intervalTicks = "IntervalTicks"
        case dayOfWeek = "DayOfWeek"
        case maxRuntimeTicks = "MaxRuntimeTicks"
    }

}
