//
// TaskState.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Enum TaskState. */
public enum TaskState: String, Codable {
    case idle = "Idle"
    case cancelling = "Cancelling"
    case running = "Running"
}