//
// TaskCompletionStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Enum TaskCompletionStatus. */
public enum TaskCompletionStatus: String, Codable {
    case completed = "Completed"
    case failed = "Failed"
    case cancelled = "Cancelled"
    case aborted = "Aborted"
}