//
// TransportStreamTimestamp.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum TransportStreamTimestamp: String, Codable {
    case _none = "None"
    case zero = "Zero"
    case valid = "Valid"
}