//
// TranscodeSeekInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum TranscodeSeekInfo: String, Codable {
    case auto = "Auto"
    case bytes = "Bytes"
}