//
// TranscodingProfile.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TranscodingProfile: Codable {

    public var container: String?
    public var type: AllOfTranscodingProfileModelType?
    public var videoCodec: String?
    public var audioCodec: String?
    public var _protocol: String?
    public var estimateContentLength: Bool?
    public var enableMpegtsM2TsMode: Bool?
    public var transcodeSeekInfo: AllOfTranscodingProfileTranscodeSeekInfo?
    public var copyTimestamps: Bool?
    public var context: AllOfTranscodingProfileContext?
    public var enableSubtitlesInManifest: Bool?
    public var maxAudioChannels: String?
    public var minSegments: Int?
    public var segmentLength: Int?
    public var breakOnNonKeyFrames: Bool?

    public init(container: String? = nil, type: AllOfTranscodingProfileModelType? = nil, videoCodec: String? = nil, audioCodec: String? = nil, _protocol: String? = nil, estimateContentLength: Bool? = nil, enableMpegtsM2TsMode: Bool? = nil, transcodeSeekInfo: AllOfTranscodingProfileTranscodeSeekInfo? = nil, copyTimestamps: Bool? = nil, context: AllOfTranscodingProfileContext? = nil, enableSubtitlesInManifest: Bool? = nil, maxAudioChannels: String? = nil, minSegments: Int? = nil, segmentLength: Int? = nil, breakOnNonKeyFrames: Bool? = nil) {
        self.container = container
        self.type = type
        self.videoCodec = videoCodec
        self.audioCodec = audioCodec
        self._protocol = _protocol
        self.estimateContentLength = estimateContentLength
        self.enableMpegtsM2TsMode = enableMpegtsM2TsMode
        self.transcodeSeekInfo = transcodeSeekInfo
        self.copyTimestamps = copyTimestamps
        self.context = context
        self.enableSubtitlesInManifest = enableSubtitlesInManifest
        self.maxAudioChannels = maxAudioChannels
        self.minSegments = minSegments
        self.segmentLength = segmentLength
        self.breakOnNonKeyFrames = breakOnNonKeyFrames
    }

    public enum CodingKeys: String, CodingKey { 
        case container = "Container"
        case type = "Type"
        case videoCodec = "VideoCodec"
        case audioCodec = "AudioCodec"
        case _protocol = "Protocol"
        case estimateContentLength = "EstimateContentLength"
        case enableMpegtsM2TsMode = "EnableMpegtsM2TsMode"
        case transcodeSeekInfo = "TranscodeSeekInfo"
        case copyTimestamps = "CopyTimestamps"
        case context = "Context"
        case enableSubtitlesInManifest = "EnableSubtitlesInManifest"
        case maxAudioChannels = "MaxAudioChannels"
        case minSegments = "MinSegments"
        case segmentLength = "SegmentLength"
        case breakOnNonKeyFrames = "BreakOnNonKeyFrames"
    }

}
