//
// UserDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Class UserDto. */

public struct UserDto: Codable {

    /** Gets or sets the name. */
    public var name: String?
    /** Gets or sets the server identifier. */
    public var serverId: String?
    /** Gets or sets the name of the server.  This is not used by the server and is for client-side usage only. */
    public var serverName: String?
    /** Gets or sets the id. */
    public var _id: UUID?
    /** Gets or sets the primary image tag. */
    public var primaryImageTag: String?
    /** Gets or sets a value indicating whether this instance has password. */
    public var hasPassword: Bool?
    /** Gets or sets a value indicating whether this instance has configured password. */
    public var hasConfiguredPassword: Bool?
    /** Gets or sets a value indicating whether this instance has configured easy password. */
    public var hasConfiguredEasyPassword: Bool?
    /** Gets or sets whether async login is enabled or not. */
    public var enableAutoLogin: Bool?
    /** Gets or sets the last login date. */
    public var lastLoginDate: Date?
    /** Gets or sets the last activity date. */
    public var lastActivityDate: Date?
    /** Gets or sets the configuration. */
    public var configuration: AllOfUserDtoConfiguration?
    /** Gets or sets the policy. */
    public var policy: AllOfUserDtoPolicy?
    /** Gets or sets the primary image aspect ratio. */
    public var primaryImageAspectRatio: Double?

    public init(name: String? = nil, serverId: String? = nil, serverName: String? = nil, _id: UUID? = nil, primaryImageTag: String? = nil, hasPassword: Bool? = nil, hasConfiguredPassword: Bool? = nil, hasConfiguredEasyPassword: Bool? = nil, enableAutoLogin: Bool? = nil, lastLoginDate: Date? = nil, lastActivityDate: Date? = nil, configuration: AllOfUserDtoConfiguration? = nil, policy: AllOfUserDtoPolicy? = nil, primaryImageAspectRatio: Double? = nil) {
        self.name = name
        self.serverId = serverId
        self.serverName = serverName
        self._id = _id
        self.primaryImageTag = primaryImageTag
        self.hasPassword = hasPassword
        self.hasConfiguredPassword = hasConfiguredPassword
        self.hasConfiguredEasyPassword = hasConfiguredEasyPassword
        self.enableAutoLogin = enableAutoLogin
        self.lastLoginDate = lastLoginDate
        self.lastActivityDate = lastActivityDate
        self.configuration = configuration
        self.policy = policy
        self.primaryImageAspectRatio = primaryImageAspectRatio
    }

    public enum CodingKeys: String, CodingKey { 
        case name = "Name"
        case serverId = "ServerId"
        case serverName = "ServerName"
        case _id = "Id"
        case primaryImageTag = "PrimaryImageTag"
        case hasPassword = "HasPassword"
        case hasConfiguredPassword = "HasConfiguredPassword"
        case hasConfiguredEasyPassword = "HasConfiguredEasyPassword"
        case enableAutoLogin = "EnableAutoLogin"
        case lastLoginDate = "LastLoginDate"
        case lastActivityDate = "LastActivityDate"
        case configuration = "Configuration"
        case policy = "Policy"
        case primaryImageAspectRatio = "PrimaryImageAspectRatio"
    }

}
