//
// UsersAuthenticateByNameBody1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The M:Jellyfin.Api.Controllers.UserController.AuthenticateUserByName(Jellyfin.Api.Models.UserDtos.AuthenticateUserByName) request. */

public struct UsersAuthenticateByNameBody1: Codable {

    /** Gets or sets the username. */
    public var username: String?
    /** Gets or sets the plain text password. */
    public var pw: String?
    /** Gets or sets the sha1-hashed password. */
    public var password: String?

    public init(username: String? = nil, pw: String? = nil, password: String? = nil) {
        self.username = username
        self.pw = pw
        self.password = password
    }

    public enum CodingKeys: String, CodingKey { 
        case username = "Username"
        case pw = "Pw"
        case password = "Password"
    }

}
