//
// UtcTimeResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Class UtcTimeResponse. */

public struct UtcTimeResponse: Codable {

    /** Gets the UTC time when request has been received. */
    public var requestReceptionTime: Date?
    /** Gets the UTC time when response has been sent. */
    public var responseTransmissionTime: Date?

    public init(requestReceptionTime: Date? = nil, responseTransmissionTime: Date? = nil) {
        self.requestReceptionTime = requestReceptionTime
        self.responseTransmissionTime = responseTransmissionTime
    }

    public enum CodingKeys: String, CodingKey { 
        case requestReceptionTime = "RequestReceptionTime"
        case responseTransmissionTime = "ResponseTransmissionTime"
    }

}
