//
// VersionInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Defines the MediaBrowser.Model.Updates.VersionInfo class. */

public struct VersionInfo: Codable {

    /** Gets or sets the version. */
    public var version: String?
    /** Gets the version as a System.Version. */
    public var versionNumber: AllOfVersionInfoVersionNumber?
    /** Gets or sets the changelog for this version. */
    public var changelog: String?
    /** Gets or sets the ABI that this version was built against. */
    public var targetAbi: String?
    /** Gets or sets the source URL. */
    public var sourceUrl: String?
    /** Gets or sets a checksum for the binary. */
    public var checksum: String?
    /** Gets or sets a timestamp of when the binary was built. */
    public var timestamp: String?
    /** Gets or sets the repository name. */
    public var repositoryName: String?
    /** Gets or sets the repository url. */
    public var repositoryUrl: String?

    public init(version: String? = nil, versionNumber: AllOfVersionInfoVersionNumber? = nil, changelog: String? = nil, targetAbi: String? = nil, sourceUrl: String? = nil, checksum: String? = nil, timestamp: String? = nil, repositoryName: String? = nil, repositoryUrl: String? = nil) {
        self.version = version
        self.versionNumber = versionNumber
        self.changelog = changelog
        self.targetAbi = targetAbi
        self.sourceUrl = sourceUrl
        self.checksum = checksum
        self.timestamp = timestamp
        self.repositoryName = repositoryName
        self.repositoryUrl = repositoryUrl
    }

    public enum CodingKeys: String, CodingKey { 
        case version
        case versionNumber = "VersionNumber"
        case changelog
        case targetAbi
        case sourceUrl
        case checksum
        case timestamp
        case repositoryName
        case repositoryUrl
    }

}
