//
// XmlAttribute.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Defines the MediaBrowser.Model.Dlna.XmlAttribute. */

public struct XmlAttribute: Codable {

    /** Gets or sets the name of the attribute. */
    public var name: String?
    /** Gets or sets the value of the attribute. */
    public var value: String?

    public init(name: String? = nil, value: String? = nil) {
        self.name = name
        self.value = value
    }

    public enum CodingKeys: String, CodingKey { 
        case name = "Name"
        case value = "Value"
    }

}
