update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta_ios do
    increment_build_number(xcodeproj: "JellyfinPlayer.xcodeproj")
    gym(output_name: "JellyfinPlayer.ipa", scheme: "JellyfinPlayer")
    upload_to_testflight
  end
  desc "Push a new beta build to TestFlight (tvOS)"
  lane :beta_tvos do
    increment_build_number(xcodeproj: "JellyfinPlayer.xcodeproj")
    gym(output_name: "JellyfinPlayer.ipa", scheme: "JellyfinPlayer tvOS")
    upload_to_testflight
  end
end