update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build targets"
  lane :build do
    gym
  end
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "JellyfinPlayer.xcodeproj")
    gym(output_name: "JellyfinPlayer.ipa")
    upload_to_testflight
  end
end
