# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build targets"
  lane :build do
    gym
  end
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "JellyfinPlayer.xcodeproj")
    gym(output_name: "JellyfinPlayer.ipa")
    identifier_v = get_version_number(xcodeproj: "JellyfinPlayer.xcodeproj")
    identifier_s = get_info_plist_value(path: "JellyfinPlayer/Info.plist", key: "CFBundleVersion")
    upload_symbols_to_sentry(
      org_slug: 'aidenvigue',
      project_slug: 'jellyfin-swift-ios',
      dsym_path: "JellyfinPlayer.app.dSYM.zip"
    )
    set_github_release(
      repository_name: "jellyfin/JellyfinPlayer",
      name: "Release #{identifier_v}@#{identifier_s}",
      tag_name: "v#{identifier_s}",
      description: (File.read("Release Notes.rtf") rescue "No changelog provided"),
      commitish: "main",
      upload_assets: ["JellyfinPlayer.ipa"]
    )
    upload_to_testflight
    dynatrace_process_symbols(
      appId: "8c1f6941-ec78-480c-b589-b41aca29a52e",
      os: "ios",
      bundleId: "me.vigue.jellyfin",
      versionStr: identifier_v,
      version: identifier_s,
      server: "https://ofa89490.live.dynatrace.com",
      symbolsfile: "JellyfinPlayer.app.dSYM.zip"
    )
  end
end
