# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 16 Pro",
  "iPad Pro 13-inch (M4)",
])

languages([
  "en-US"
#   "de-DE",
#   "it-IT",
#   ["pt", "pt_BR"] # Portuguese with Brazilian locale
])

ios_version("18.5")

# The name of the scheme which contains the UI Tests
scheme("Swiftfin Screenshots")

# Where should the resulting screenshots be stored?
output_directory("./Swiftfin Screenshots/screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
# clear_previous_screenshots(true)
override_status_bar_arguments("override --time \"12:30\" --batteryState discharging --batteryLevel 100 --cellularBars 4")

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
