name: "Unused Strings 🧹"

on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches: [ main ]

jobs:
  unused-strings:
    name: "Unused Strings 🧹"
    if: github.event.pull_request.draft == false
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find Unused Strings
        run: swift Scripts/Translations/FindUnusedStrings.swift
